/**
 * UI strings for the rail variants. Prototype-local on purpose: the variant
 * the user picks moves its strings into the session-core i18n tables; the
 * others are deleted with their copy.
 */

import type { Family, FleetState } from './model';

const zh = {
  prototype: '右栏原型',
  current: '现行',
  close: '收起右栏',
  approve: '批准',
  reject: '拒绝',
  answer: '去回答',
  review: '查看',
  openAgent: '打开',
  from: '来自',
  main: '主智能体',
  now: '现在',
  context: '上下文',
  compactions: '次压缩',
  cost: '费用',
  cache: '缓存命中',
  turns: '轮',
  agents: '智能体',
  ago: (s: string) => `${s}前`,
  state: { waiting: '等你', running: '在飞', done: '已回报', failed: '失败', stopped: '已停止' } satisfies Record<FleetState, string>,
  family: { opus: 'Opus', sol: 'Sol', luna: 'Luna', ds: 'DeepSeek', other: '其他' } satisfies Record<Family, string>,
  // A · swimlanes
  aTitle: '作战地图',
  aWindow: (h: number) => `最近 ${h} 小时`,
  aLanes: '泳道',
  aEarlier: (n: number) => `另有 ${n} 个更早结束`,
  aCompaction: '压缩',
  aYou: '你的消息',
  // B · cockpit
  bTitle: '驾驶舱',
  bCaution: '主告警',
  bClear: '无待处理',
  bArray: '智能体阵列',
  bInFlight: '在飞',
  bElapsed: '已运行',
  bUntil: (k: string) => `距压缩约 ${k}`,
  // C · inbox
  cHeadline: (n: number) => (n === 0 ? '没有等你的事' : `${n} 件事等你`),
  cZero: '智能体都在自己跑。有新的审批或问题会先出现在这里。',
  cReports: '新回报',
  cReportsHint: '最近一小时',
  cFailed: '没跑完',
  cInFlight: (n: number) => `${n} 个还在跑`,
  cMarkRead: '全部已读',
  cKeys: 'A 批准 · R 拒绝',
  // D · companion stream
  dTitle: '伴随流',
  dYou: '你',
  dDispatched: (n: number) => `派出 ${n} 个`,
  dReturned: (n: number) => `${n} 个回报`,
  dCompacted: '上下文已压缩',
  dEarlier: (agents: number, compactions: number) => `更早 · ${agents} 个智能体 · ${compactions} 次压缩`,
  dQuiet: '这段时间没有新动静',
  dMainSays: '主智能体正在说',
};

type Copy = typeof zh;

const en: Copy = {
  prototype: 'Rail prototype',
  current: 'Current',
  close: 'Hide panel',
  approve: 'Approve',
  reject: 'Reject',
  answer: 'Answer',
  review: 'Review',
  openAgent: 'Open',
  from: 'From',
  main: 'Main agent',
  now: 'Now',
  context: 'Context',
  compactions: 'compactions',
  cost: 'Cost',
  cache: 'Cache hits',
  turns: 'turns',
  agents: 'Agents',
  ago: (s) => `${s} ago`,
  state: { waiting: 'Needs you', running: 'In flight', done: 'Reported', failed: 'Failed', stopped: 'Stopped' },
  family: { opus: 'Opus', sol: 'Sol', luna: 'Luna', ds: 'DeepSeek', other: 'Other' },
  aTitle: 'Battle map',
  aWindow: (h) => `Last ${h} hours`,
  aLanes: 'Lanes',
  aEarlier: (n) => `${n} more ended earlier`,
  aCompaction: 'Compacted',
  aYou: 'Your messages',
  bTitle: 'Cockpit',
  bCaution: 'Master caution',
  bClear: 'Nothing pending',
  bArray: 'Agent array',
  bInFlight: 'In flight',
  bElapsed: 'Running',
  bUntil: (k) => `~${k} to compaction`,
  cHeadline: (n) => (n === 0 ? 'Nothing needs you' : n === 1 ? '1 thing needs you' : `${n} things need you`),
  cZero: 'The agents are running on their own. New approvals and questions land here first.',
  cReports: 'New reports',
  cReportsHint: 'Last hour',
  cFailed: 'Did not finish',
  cInFlight: (n) => `${n} still running`,
  cMarkRead: 'Mark all read',
  cKeys: 'A approve · R reject',
  dTitle: 'Companion stream',
  dYou: 'You',
  dDispatched: (n) => `Dispatched ${n}`,
  dReturned: (n) => `${n} reported back`,
  dCompacted: 'Context compacted',
  dEarlier: (agents, compactions) => `Earlier · ${agents} agents · ${compactions} compactions`,
  dQuiet: 'Nothing new in this stretch',
  dMainSays: 'Main agent is saying',
};

export function railCopy(locale: 'en' | 'zh'): Copy {
  return locale === 'zh' ? zh : en;
}
