/**
 * Built-in skins. One source of truth: the same declarative shape a user file
 * in `~/.kiki/themes/` uses, so a built-in skin and a user skin travel through
 * exactly the same resolve/apply path (`lib/skins/apply.ts`).
 *
 * Design intent per skin lives in its `description`; the palettes were checked
 * for WCAG AA on every step of the surface ladder (canvas / paper / panel)
 * before landing — see `skins.test.ts`, which re-checks it on every run.
 *
 * `paper` is special: it is the product's own identity and carries no colors
 * here. Its values are the `@theme` defaults in `index.css`, so the default
 * skin is literally "apply nothing" and the shell owner stays the single
 * author of the base palette.
 */

import type { SkinFile } from '@kiki/protocol';
import type { I18nKey } from '@kiki/session-core/i18n';

/** The skin id that means "the base palette in index.css". */
export const DEFAULT_SKIN_ID = 'paper';

/**
 * Built-in ids that no longer ship. A stored selection of one moves to the
 * default (see `normalizeSkinPrefs`) instead of failing to resolve.
 */
export const RETIRED_BUILTIN_SKIN_IDS: ReadonlySet<string> = new Set(['sand', 'slate']);

const FONT_SANS_NEUTRAL =
  "'Instrument Sans Variable', 'Instrument Sans', ui-sans-serif, system-ui, 'Segoe UI', 'PingFang SC', 'Noto Sans SC', sans-serif";
const FONT_DISPLAY_NEUTRAL =
  "'Instrument Sans Variable', 'Instrument Sans', ui-sans-serif, system-ui, 'Segoe UI', 'PingFang SC', 'Noto Sans SC', sans-serif";

export const BUILTIN_SKINS: readonly SkinFile[] = [
  {
    kind: 'kiki-skin',
    version: 1,
    id: DEFAULT_SKIN_ID,
    name: 'Paper',
    description: 'Warm paper, brown ink, a rust mark. Kiki\'s own voice.',
    variants: { light: {}, dark: {} },
  },
  {
    kind: 'kiki-skin',
    version: 1,
    id: 'linen',
    name: 'Linen',
    description: 'Unbleached cloth and ink-blue thread. Plain, calm, cool.',
    variants: {
      light: {
        colors: {
          canvas: '#e9e8e4',
          paper: '#f7f6f3',
          panel: '#fdfdfb',
          hairline: '#dfddd7',
          hairlineStrong: '#c9c6be',
          ink: '#1a1b1e',
          inkSoft: '#4b4e55',
          inkFaint: '#5f6269',
          accent: '#2d52c4',
          accentDeep: '#1f3d99',
          accentSoft: '#e2e8f8',
          accentInk: '#2446ab',
          onAccent: '#ffffff',
          sectionInk: '#2446ab',
          selected: '#dfe5f5',
          selectedInk: '#1f3d99',
          attention: '#b83a0b',
          attentionSoft: '#fae5d8',
          amberInk: '#8a3d0c',
          amberCard: '#f7ecd8',
          amberRule: '#c9942f',
          success: '#2f6b3a',
          danger: '#b42318',
          onDanger: '#ffffff',
          bubbleUser: '#ecebe7',
          scrollbar: '#d3d1cb',
          scrollbarHover: '#b9b6ae',
          termScrollbar: '#3c3f45',
          shell: '#1b1c1f',
          shellInk: '#d9dadd',
          shellInkStrong: '#f1f2f4',
          shellInkSoft: '#8b8e95',
          shellDanger: '#f0a39c',
          shellHairline: '#33353a',
          shellHover: '#26282c',
          shadowInk: '#16171a',
        },
      },
      dark: {
        colors: {
          canvas: '#0f1012',
          paper: '#16171a',
          panel: '#1c1e22',
          hairline: '#282a2f',
          hairlineStrong: '#3a3d44',
          ink: '#e9eaec',
          inkSoft: '#b0b3ba',
          inkFaint: '#8f939b',
          accent: '#7c9bff',
          accentDeep: '#a3b9ff',
          accentSoft: '#1a2238',
          accentInk: '#8fa9ff',
          onAccent: '#0b1430',
          sectionInk: '#9fb3ec',
          selected: '#1b2438',
          selectedInk: '#a9bfff',
          attention: '#ff9a5c',
          attentionSoft: '#3a2415',
          amberInk: '#e0a63c',
          amberCard: '#2a2113',
          amberRule: '#7c5c22',
          success: '#7fb88a',
          danger: '#f2877c',
          onDanger: '#2b0603',
          bubbleUser: '#202227',
          scrollbar: '#34373d',
          scrollbarHover: '#474a52',
          termScrollbar: '#474a52',
          shell: '#0a0b0d',
          shellInk: '#d0d3d9',
          shellInkStrong: '#eef0f3',
          shellInkSoft: '#868a93',
          shellDanger: '#f0a39c',
          shellHairline: '#202227',
          shellHover: '#17181b',
          shadowInk: '#000000',
        },
      },
    },
  },
  {
    kind: 'kiki-skin',
    version: 1,
    id: 'graphite',
    name: 'Graphite',
    description: 'Brushed steel and a cyan signal. Cool, exact, quiet.',
    variants: {
      light: {
        colors: {
          canvas: '#dfe3e8',
          paper: '#f1f3f6',
          panel: '#fafbfc',
          hairline: '#d3d8df',
          hairlineStrong: '#b4bcc7',
          ink: '#12161c',
          inkSoft: '#3f4753',
          inkFaint: '#535c69',
          accent: '#0b6e87',
          accentDeep: '#085265',
          accentSoft: '#d9ecf1',
          accentInk: '#0a5a6f',
          onAccent: '#ffffff',
          sectionInk: '#2f4a5c',
          selected: '#d7e9ee',
          selectedInk: '#0a5a6f',
          attention: '#b0400c',
          attentionSoft: '#f1e5df',
          amberInk: '#86440b',
          amberCard: '#f5ead7',
          amberRule: '#a1744d',
          success: '#1f6b43',
          danger: '#b3261e',
          onDanger: '#ffffff',
          bubbleUser: '#e6e8eb',
          scrollbar: '#c2c6cb',
          scrollbarHover: '#aeb2b7',
          termScrollbar: '#4f5153',
          shell: '#111417',
          shellInk: '#d4d5d5',
          shellInkStrong: '#f1f1f1',
          shellInkSoft: '#888a8b',
          shellDanger: '#f0a39c',
          shellHairline: '#323537',
          shellHover: '#24272a',
          shadowInk: '#0d0f14',
        },
        fonts: { display: FONT_DISPLAY_NEUTRAL, sans: FONT_SANS_NEUTRAL },
      },
      dark: {
        colors: {
          canvas: '#0d1014',
          paper: '#14181d',
          panel: '#1a1f26',
          hairline: '#262d36',
          hairlineStrong: '#3a4450',
          ink: '#e3e8ee',
          inkSoft: '#a9b2bd',
          inkFaint: '#8a949f',
          accent: '#4cc3dc',
          accentDeep: '#79d2e5',
          accentSoft: '#10272d',
          accentInk: '#6fd0e4',
          onAccent: '#04191e',
          sectionInk: '#9fb6c6',
          selected: '#12272d',
          selectedInk: '#7dd6e8',
          attention: '#ff9a5c',
          attentionSoft: '#3f332f',
          amberInk: '#e6ad4f',
          amberCard: '#29210f',
          amberRule: '#846634',
          success: '#6fcf97',
          danger: '#f58e86',
          onDanger: '#2b0603',
          bubbleUser: '#22272c',
          scrollbar: '#383b40',
          scrollbarHover: '#4d5155',
          termScrollbar: '#484a4c',
          shell: '#080a0d',
          shellInk: '#d3d3d3',
          shellInkStrong: '#f0f0f0',
          shellInkSoft: '#848486',
          shellDanger: '#f0a39c',
          shellHairline: '#2b2c2f',
          shellHover: '#1c1e20',
          shadowInk: '#000000',
        },
        fonts: { display: FONT_DISPLAY_NEUTRAL, sans: FONT_SANS_NEUTRAL },
      },
    },
  },
  {
    kind: 'kiki-skin',
    version: 1,
    id: 'forest',
    name: 'Forest',
    description: 'Pine shade and moss, with a lantern for what needs you.',
    variants: {
      light: {
        colors: {
          canvas: '#dfe5d9',
          paper: '#f1f4ec',
          panel: '#fafbf7',
          hairline: '#d2dac9',
          hairlineStrong: '#b3c0a6',
          ink: '#141a13',
          inkSoft: '#3c4a39',
          inkFaint: '#4f5d4b',
          accent: '#2f6b34',
          accentDeep: '#235027',
          accentSoft: '#dcead6',
          accentInk: '#265a2b',
          onAccent: '#ffffff',
          sectionInk: '#3d5a2a',
          selected: '#dbe8d3',
          selectedInk: '#1f5226',
          attention: '#8a4f00',
          attentionSoft: '#ede6d9',
          amberInk: '#7a4606',
          amberCard: '#f2ead3',
          amberRule: '#987645',
          success: '#2f6b34',
          danger: '#b3261e',
          onDanger: '#ffffff',
          bubbleUser: '#e6e9e1',
          scrollbar: '#c3c9bd',
          scrollbarHover: '#aeb4a9',
          termScrollbar: '#505350',
          shell: '#121612',
          shellInk: '#d4d5d4',
          shellInkStrong: '#f1f1f1',
          shellInkSoft: '#888a88',
          shellDanger: '#f0a39c',
          shellHairline: '#333733',
          shellHover: '#252925',
          shadowInk: '#0e120d',
        },
      },
      dark: {
        colors: {
          canvas: '#0b120d',
          paper: '#111a13',
          panel: '#172219',
          hairline: '#223026',
          hairlineStrong: '#34473a',
          ink: '#e2ebdf',
          inkSoft: '#a9b9a6',
          inkFaint: '#8a9c87',
          accent: '#79c07a',
          accentDeep: '#9ad09b',
          accentSoft: '#16291a',
          accentInk: '#8fcd8f',
          onAccent: '#07170a',
          sectionInk: '#b4c98f',
          selected: '#17301c',
          selectedInk: '#9ad89a',
          attention: '#f0b54a',
          attentionSoft: '#3a3a21',
          amberInk: '#e6b95a',
          amberCard: '#282112',
          amberRule: '#836e37',
          success: '#79c07a',
          danger: '#f28b82',
          onDanger: '#2b0603',
          bubbleUser: '#202921',
          scrollbar: '#363d37',
          scrollbarHover: '#4c534c',
          termScrollbar: '#474b48',
          shell: '#070c08',
          shellInk: '#d2d3d3',
          shellInkStrong: '#f0f0f0',
          shellInkSoft: '#838684',
          shellDanger: '#f0a39c',
          shellHairline: '#2a2e2b',
          shellHover: '#1b1f1c',
          shadowInk: '#000000',
        },
      },
    },
  },
  {
    kind: 'kiki-skin',
    version: 1,
    id: 'claret',
    name: 'Claret',
    description: 'Wine and cocoa after dark, blush paper by day.',
    variants: {
      light: {
        colors: {
          canvas: '#ecdfdc',
          paper: '#f8f1ef',
          panel: '#fdfaf9',
          hairline: '#e5d5d1',
          hairlineStrong: '#cfb6b0',
          ink: '#201416',
          inkSoft: '#533a3e',
          inkFaint: '#684c51',
          accent: '#a3324a',
          accentDeep: '#7a2638',
          accentSoft: '#f4dde2',
          accentInk: '#8a2940',
          onAccent: '#ffffff',
          sectionInk: '#7a2e3e',
          selected: '#f1dde0',
          selectedInk: '#8a2940',
          attention: '#a24400',
          attentionSoft: '#f2e4db',
          amberInk: '#86440b',
          amberCard: '#f5e7d6',
          amberRule: '#a5724a',
          success: '#2f6b3a',
          danger: '#b3261e',
          onDanger: '#ffffff',
          bubbleUser: '#ede6e4',
          scrollbar: '#cfc3c0',
          scrollbarHover: '#bbaeac',
          termScrollbar: '#565051',
          shell: '#1a1214',
          shellInk: '#d6d4d5',
          shellInkStrong: '#f1f1f1',
          shellInkSoft: '#8c888a',
          shellDanger: '#f0a39c',
          shellHairline: '#3a3335',
          shellHover: '#2c2527',
          shadowInk: '#160e0f',
        },
      },
      dark: {
        colors: {
          canvas: '#140c0d',
          paper: '#1b1112',
          panel: '#231618',
          hairline: '#342225',
          hairlineStrong: '#4b3236',
          ink: '#f1e4e2',
          inkSoft: '#c3aaa7',
          inkFaint: '#a18985',
          accent: '#ef8a98',
          accentDeep: '#f3a7b2',
          accentSoft: '#3a1c22',
          accentInk: '#f39eaa',
          onAccent: '#2a0a10',
          sectionInk: '#e0a98f',
          selected: '#3a1d24',
          selectedInk: '#f7b3bd',
          attention: '#f6b35e',
          attentionSoft: '#452f23',
          amberInk: '#e8b060',
          amberCard: '#2b1f12',
          amberRule: '#89663b',
          success: '#86c39a',
          danger: '#ff8f86',
          onDanger: '#2b0603',
          bubbleUser: '#2a2021',
          scrollbar: '#403738',
          scrollbarHover: '#564d4d',
          termScrollbar: '#4c4848',
          shell: '#0d0808',
          shellInk: '#d3d3d3',
          shellInkStrong: '#f0f0f0',
          shellInkSoft: '#868484',
          shellDanger: '#f0a39c',
          shellHairline: '#2f2b2b',
          shellHover: '#201c1c',
          shadowInk: '#000000',
        },
      },
    },
  },
  {
    kind: 'kiki-skin',
    version: 1,
    id: 'heather',
    name: 'Heather',
    description: 'Lavender haze, dusty mauve, a sage mark. Colour without shouting.',
    variants: {
      light: {
        colors: {
          canvas: '#e6e2ea',
          paper: '#f4f2f6',
          panel: '#fbfafc',
          hairline: '#dbd6e1',
          hairlineStrong: '#c0b8ca',
          ink: '#1b1820',
          inkSoft: '#48424f',
          inkFaint: '#5b5463',
          accent: '#7a4f8c',
          accentDeep: '#5c3b69',
          accentSoft: '#ebe0f0',
          accentInk: '#654075',
          onAccent: '#ffffff',
          sectionInk: '#5e4a78',
          selected: '#dde8df',
          selectedInk: '#2e5a3f',
          attention: '#a4441c',
          attentionSoft: '#f1e4e1',
          amberInk: '#86440b',
          amberCard: '#f4e8d8',
          amberRule: '#a3734e',
          success: '#2e6a45',
          danger: '#b0283a',
          onDanger: '#ffffff',
          bubbleUser: '#e9e7eb',
          scrollbar: '#cac6ce',
          scrollbarHover: '#b5b2ba',
          termScrollbar: '#535256',
          shell: '#17151a',
          shellInk: '#d5d5d6',
          shellInkStrong: '#f1f1f1',
          shellInkSoft: '#8b8a8c',
          shellDanger: '#f0a39c',
          shellHairline: '#37363a',
          shellHover: '#2a282c',
          shadowInk: '#131116',
        },
      },
      dark: {
        colors: {
          canvas: '#141219',
          paper: '#1a1820',
          panel: '#211e28',
          hairline: '#2e2a37',
          hairlineStrong: '#433d4f',
          ink: '#ebe6f0',
          inkSoft: '#b7aec2',
          inkFaint: '#978ea3',
          accent: '#c9a3dc',
          accentDeep: '#d6bae5',
          accentSoft: '#2c2234',
          accentInk: '#d3b3e3',
          onAccent: '#1c1024',
          sectionInk: '#b8a6d8',
          selected: '#1d2b23',
          selectedInk: '#a6d2b3',
          attention: '#f2a883',
          attentionSoft: '#423437',
          amberInk: '#e4b268',
          amberCard: '#2a2217',
          amberRule: '#866a44',
          success: '#8ccaa0',
          danger: '#f2909d',
          onDanger: '#2b0603',
          bubbleUser: '#29262f',
          scrollbar: '#3f3c44',
          scrollbarHover: '#54525a',
          termScrollbar: '#4c4b4e',
          shell: '#0d0c10',
          shellInk: '#d3d3d4',
          shellInkStrong: '#f0f0f1',
          shellInkSoft: '#868688',
          shellDanger: '#f0a39c',
          shellHairline: '#2f2e31',
          shellHover: '#201f23',
          shadowInk: '#000000',
        },
      },
    },
  },
  {
    kind: 'kiki-skin',
    version: 1,
    id: 'nocturne',
    name: 'Nocturne',
    description: 'Dark only. A clear-night navy lit by starlight gold.',
    variants: {
      dark: {
        colors: {
          canvas: '#070b16',
          paper: '#0c1222',
          panel: '#121a2e',
          hairline: '#1d2740',
          hairlineStrong: '#2f3c5c',
          ink: '#e6eaf5',
          inkSoft: '#aab3cb',
          inkFaint: '#8b95b0',
          accent: '#f2c65c',
          accentDeep: '#f5d485',
          accentSoft: '#2a2412',
          accentInk: '#f5d27a',
          onAccent: '#1d1603',
          sectionInk: '#a9b8e6',
          selected: '#162342',
          selectedInk: '#f5d27a',
          attention: '#ff9e7a',
          attentionSoft: '#34201c',
          amberInk: '#f2c65c',
          amberCard: '#241f10',
          amberRule: '#88723c',
          success: '#7fd1a6',
          danger: '#ff8f9a',
          onDanger: '#2b0603',
          bubbleUser: '#1b2131',
          scrollbar: '#343843',
          scrollbarHover: '#4a4e59',
          termScrollbar: '#46474d',
          shell: '#05070e',
          shellInk: '#d2d2d4',
          shellInkStrong: '#f0f0f1',
          shellInkSoft: '#828386',
          shellDanger: '#f0a39c',
          shellHairline: '#282a30',
          shellHover: '#191b21',
          shadowInk: '#000000',
        },
      },
    },
  },
  {
    kind: 'kiki-skin',
    version: 1,
    id: 'contrast',
    name: 'High contrast',
    description: 'Solid borders, AAA text, one bold signal per role. Nothing implied.',
    variants: {
      light: {
        colors: {
          canvas: '#e7e9ec',
          paper: '#ffffff',
          panel: '#ffffff',
          hairline: '#6e7781',
          hairlineStrong: '#20252c',
          ink: '#0e1116',
          inkSoft: '#20252c',
          inkFaint: '#353b44',
          accent: '#0349b4',
          accentDeep: '#023787',
          accentSoft: '#dbe7fb',
          accentInk: '#023b95',
          onAccent: '#ffffff',
          sectionInk: '#0e1116',
          selected: '#dbe7fb',
          selectedInk: '#023b95',
          attention: '#a2280a',
          attentionSoft: '#fde3d9',
          amberInk: '#6b3d00',
          amberCard: '#fdf0cf',
          amberRule: '#8a5a00',
          success: '#055d20',
          danger: '#a0111f',
          onDanger: '#ffffff',
          bubbleUser: '#f3f3f3',
          scrollbar: '#c9cbce',
          scrollbarHover: '#b3b5b9',
          termScrollbar: '#4d4f53',
          shell: '#0e1116',
          shellInk: '#d4d4d5',
          shellInkStrong: '#f1f1f1',
          shellInkSoft: '#86888a',
          shellDanger: '#f0a39c',
          shellHairline: '#303237',
          shellHover: '#212429',
          shadowInk: '#0a0c0f',
        },
        fonts: { display: FONT_DISPLAY_NEUTRAL, sans: FONT_SANS_NEUTRAL },
        shape: { radius: 8 },
      },
      dark: {
        colors: {
          canvas: '#010409',
          paper: '#0a0c10',
          panel: '#12161c',
          hairline: '#7a828e',
          hairlineStrong: '#c9d1d9',
          ink: '#f0f3f6',
          inkSoft: '#dfe3e8',
          inkFaint: '#c3cad3',
          accent: '#71b7ff',
          accentDeep: '#94c9ff',
          accentSoft: '#0d2240',
          accentInk: '#91cbff',
          onAccent: '#010409',
          sectionInk: '#f0f3f6',
          selected: '#0d2240',
          selectedInk: '#91cbff',
          attention: '#ffb757',
          attentionSoft: '#2e2003',
          amberInk: '#f0b72f',
          amberCard: '#241a00',
          amberRule: '#9c6d00',
          success: '#4ae168',
          danger: '#ff9492',
          onDanger: '#2b0603',
          bubbleUser: '#1a1c20',
          scrollbar: '#313438',
          scrollbarHover: '#494c50',
          termScrollbar: '#434549',
          shell: '#010409',
          shellInk: '#d1d2d3',
          shellInkStrong: '#f0f0f0',
          shellInkSoft: '#808284',
          shellDanger: '#f0a39c',
          shellHairline: '#25272b',
          shellHover: '#15181d',
          shadowInk: '#000000',
        },
        fonts: { display: FONT_DISPLAY_NEUTRAL, sans: FONT_SANS_NEUTRAL },
        shape: { radius: 8 },
      },
    },
  },
];

export function findBuiltinSkin(id: string): SkinFile | undefined {
  return BUILTIN_SKINS.find((skin) => skin.id === id);
}

/**
 * Localized descriptions for the built-in skins. The English `description`
 * above stays on the skin itself (it travels into exported skin files); the
 * picker shows this key instead. User skins have no key and show their own text.
 */
export const BUILTIN_SKIN_DESCRIPTION_KEYS = {
  paper: 'st.skin.desc.paper',
  linen: 'st.skin.desc.linen',
  graphite: 'st.skin.desc.graphite',
  forest: 'st.skin.desc.forest',
  claret: 'st.skin.desc.claret',
  heather: 'st.skin.desc.heather',
  nocturne: 'st.skin.desc.nocturne',
  contrast: 'st.skin.desc.contrast',
} as const satisfies Readonly<Record<string, I18nKey>>;

export function builtinSkinDescriptionKey(id: string | undefined): I18nKey | undefined {
  return id !== undefined && Object.hasOwn(BUILTIN_SKIN_DESCRIPTION_KEYS, id)
    ? BUILTIN_SKIN_DESCRIPTION_KEYS[id as keyof typeof BUILTIN_SKIN_DESCRIPTION_KEYS]
    : undefined;
}
