/** Built-ins use the same declarative resolve/apply path as user skin files. */
import type { SkinFile } from '@kiki/protocol';
import type { I18nKey } from '@kiki/session-core/i18n';

/** Paper / Inkstone is the default family in both brightness modes. */
export const DEFAULT_SKIN_ID = 'paper';

/** Stored retired built-ins normalize to the default without dropping tweaks. */
export const RETIRED_BUILTIN_SKIN_IDS: ReadonlySet<string> = new Set([
  'linen', 'graphite', 'forest', 'claret', 'heather', 'nocturne', 'sand', 'slate',
]);

const FONT_SANS_NEUTRAL =
  "'Instrument Sans Variable', 'Instrument Sans', ui-sans-serif, system-ui, 'Segoe UI', 'PingFang SC', 'Noto Sans SC', sans-serif";
const FONT_DISPLAY_NEUTRAL = FONT_SANS_NEUTRAL;

export const BUILTIN_SKINS: readonly SkinFile[] = [
  {
    kind: 'kiki-skin', version: 1, id: DEFAULT_SKIN_ID,
    name: '纸色 Paper × 墨砚 Inkstone',
    description: 'Warm white paper and ink-blue marks; cool charcoal and copper after dark.',
    variants: {
      light: { colors: {
        canvas: '#F2EFE8',
        paper: '#FBFAF6',
        panel: '#FFFDFA',
        hairline: '#E4DDD0',
        hairlineStrong: '#CDC3B1',
        ink: '#1B1A17',
        inkSoft: '#4B453E',
        inkFaint: '#665E54',
        accent: '#C8401A',
        accentDeep: '#9C3012',
        accentSoft: '#F8E3D8',
        accentInk: '#9C3012',
        onAccent: '#FFFFFF',
        sectionInk: '#4B453E',
        selected: '#DFE8F0',
        selectedInk: '#1D4D6D',
        attention: '#B33A12',
        attentionSoft: '#FAE3D7',
        amberInk: '#87480B',
        amberCard: '#F8EEDD',
        amberRule: '#D9A441',
        success: '#2F6B45',
        danger: '#B0261E',
        onDanger: '#FFFFFF',
        bubbleUser: '#EEE8DC',
        scrollbar: '#D8D0C1',
        scrollbarHover: '#C4BAA8',
        termScrollbar: '#4A4238',
        shell: '#1F1B16',
        shellInk: '#E8DCC4',
        shellInkStrong: '#F3E9D8',
        shellInkSoft: '#9B8E7A',
        shellDanger: '#D9A08A',
        shellHairline: '#332D24',
        shellHover: '#2A251D',
        shadowInk: '#1B1A17',
      } },
      dark: { colors: {
        canvas: '#13191C',
        paper: '#1B2226',
        panel: '#252D31',
        hairline: '#354047',
        hairlineStrong: '#596870',
        ink: '#EEEAE2',
        inkSoft: '#C1C5C5',
        inkFaint: '#A2ACAF',
        accent: '#EB946F',
        accentDeep: '#F4B08F',
        accentSoft: '#382A25',
        accentInk: '#F4AE8D',
        onAccent: '#261A14',
        sectionInk: '#C1C5C5',
        selected: '#24323B',
        selectedInk: '#A3CBDE',
        attention: '#F4AE8D',
        attentionSoft: '#382A25',
        amberInk: '#E6BD78',
        amberCard: '#322B20',
        amberRule: '#96783F',
        success: '#9AC6AE',
        danger: '#F1A29A',
        onDanger: '#301414',
        bubbleUser: '#293238',
        scrollbar: '#4F5F68',
        scrollbarHover: '#74838C',
        termScrollbar: '#526068',
        shell: '#101518',
        shellInk: '#D1D9DA',
        shellInkStrong: '#F0F2EF',
        shellInkSoft: '#9AA7AB',
        shellDanger: '#F1A29A',
        shellHairline: '#354047',
        shellHover: '#202B30',
        shadowInk: '#000000',
      } },
    },
  },
  {
    kind: 'kiki-skin', version: 1, id: 'porcelain',
    name: '瓷白 Porcelain × 深海 Deepwater',
    description: 'Cool white paper and cobalt details; layered navy and mist-blue controls at night.',
    variants: {
      light: { colors: {
        canvas: '#E7EDF4',
        paper: '#F8FBFF',
        panel: '#FFFFFF',
        hairline: '#D2DDE9',
        hairlineStrong: '#A9B9CA',
        ink: '#17283D',
        inkSoft: '#405570',
        inkFaint: '#516279',
        accent: '#2856A6',
        accentDeep: '#1B3F84',
        accentSoft: '#E2EBFA',
        accentInk: '#204986',
        onAccent: '#FFFFFF',
        sectionInk: '#405570',
        selected: '#DEE8F7',
        selectedInk: '#204986',
        attention: '#9C461C',
        attentionSoft: '#F9E8DC',
        amberInk: '#7E520D',
        amberCard: '#F8EED9',
        amberRule: '#B58A3B',
        success: '#28664B',
        danger: '#AF343E',
        onDanger: '#FFFFFF',
        bubbleUser: '#E6EDF6',
        scrollbar: '#B6C5D6',
        scrollbarHover: '#8B9FB5',
        termScrollbar: '#52657C',
        shell: '#142033',
        shellInk: '#D8E3F1',
        shellInkStrong: '#F2F7FF',
        shellInkSoft: '#9CACC2',
        shellDanger: '#F1A6AB',
        shellHairline: '#35475E',
        shellHover: '#24354C',
        shadowInk: '#132237',
      } },
      dark: { colors: {
        canvas: '#0D1624',
        paper: '#152238',
        panel: '#1E304A',
        hairline: '#304761',
        hairlineStrong: '#586E88',
        ink: '#E4EDF9',
        inkSoft: '#B8C9E0',
        inkFaint: '#98B0CB',
        accent: '#9DAEF5',
        accentDeep: '#BAC8FF',
        accentSoft: '#283653',
        accentInk: '#BAC8FF',
        onAccent: '#17203C',
        sectionInk: '#B8C9E0',
        selected: '#293A55',
        selectedInk: '#BAD1F5',
        attention: '#F1C28C',
        attentionSoft: '#362D26',
        amberInk: '#E9C474',
        amberCard: '#332D20',
        amberRule: '#927A46',
        success: '#99D0B5',
        danger: '#F2A4AE',
        onDanger: '#351724',
        bubbleUser: '#223551',
        scrollbar: '#455F7E',
        scrollbarHover: '#6D88A8',
        termScrollbar: '#4D627C',
        shell: '#090F1A',
        shellInk: '#CFDDF0',
        shellInkStrong: '#EDF4FF',
        shellInkSoft: '#98ADC8',
        shellDanger: '#F2A4AE',
        shellHairline: '#283B53',
        shellHover: '#17273D',
        shadowInk: '#000000',
      } },
    },
  },
  {
    kind: 'kiki-skin', version: 1, id: 'celadon',
    name: '青瓷 Celadon × 夜园 Night Garden',
    description: 'Celadon glaze and soft white paper; deep pine surfaces and jade details at night.',
    variants: {
      light: { colors: {
        canvas: '#DDE7DE',
        paper: '#F2F7EF',
        panel: '#FCFEF9',
        hairline: '#C8D8CB',
        hairlineStrong: '#9DB6A7',
        ink: '#21382F',
        inkSoft: '#435D50',
        inkFaint: '#4D6253',
        accent: '#24675F',
        accentDeep: '#174F4A',
        accentSoft: '#DCECE6',
        accentInk: '#1E5650',
        onAccent: '#FFFFFF',
        sectionInk: '#435D50',
        selected: '#D7E9DE',
        selectedInk: '#20594D',
        attention: '#984B21',
        attentionSoft: '#F5E7DA',
        amberInk: '#79520D',
        amberCard: '#F6EED5',
        amberRule: '#A1843C',
        success: '#3E642A',
        danger: '#A9363C',
        onDanger: '#FFFFFF',
        bubbleUser: '#E2ECDD',
        scrollbar: '#AEC3B1',
        scrollbarHover: '#839E8B',
        termScrollbar: '#526A5D',
        shell: '#14251E',
        shellInk: '#DDE8DB',
        shellInkStrong: '#F4F9ED',
        shellInkSoft: '#9CAC9F',
        shellDanger: '#F0A8A5',
        shellHairline: '#364D3F',
        shellHover: '#253A2F',
        shadowInk: '#172A23',
      } },
      dark: { colors: {
        canvas: '#111C1A',
        paper: '#1A2925',
        panel: '#243830',
        hairline: '#354E43',
        hairlineStrong: '#597968',
        ink: '#E5EEE3',
        inkSoft: '#BDCEC1',
        inkFaint: '#9DB4A4',
        accent: '#8FCBB8',
        accentDeep: '#ACDCCD',
        accentSoft: '#283F36',
        accentInk: '#ACDCCD',
        onAccent: '#122C23',
        sectionInk: '#BDCEC1',
        selected: '#2A4036',
        selectedInk: '#B4DCC2',
        attention: '#E8BD86',
        attentionSoft: '#3B3023',
        amberInk: '#E2C47E',
        amberCard: '#34311E',
        amberRule: '#8C824A',
        success: '#C0D58F',
        danger: '#F0AAA4',
        onDanger: '#351915',
        bubbleUser: '#2B3E33',
        scrollbar: '#4E6C5B',
        scrollbarHover: '#799A85',
        termScrollbar: '#526B5D',
        shell: '#0C1512',
        shellInk: '#D2E1D4',
        shellInkStrong: '#F0F6EA',
        shellInkSoft: '#9FB5A6',
        shellDanger: '#F0AAA4',
        shellHairline: '#2D493A',
        shellHover: '#1D3026',
        shadowInk: '#000000',
      } },
    },
  },
  {
    kind: 'kiki-skin', version: 1, id: 'apricot',
    name: '杏云 Apricot × 晚霞 Afterglow',
    description: 'Apricot-white paper and berry controls; plum-charcoal layers and peach light after dark.',
    variants: {
      light: { colors: {
        canvas: '#F4DED5',
        paper: '#FFF3EB',
        panel: '#FFFAF5',
        hairline: '#DFC7C0',
        hairlineStrong: '#B698A0',
        ink: '#382C38',
        inkSoft: '#604F5C',
        inkFaint: '#6B5563',
        accent: '#A13B55',
        accentDeep: '#822C46',
        accentSoft: '#F9DFE4',
        accentInk: '#822C46',
        onAccent: '#FFFFFF',
        sectionInk: '#604F5C',
        selected: '#F2DEE2',
        selectedInk: '#7D3553',
        attention: '#934018',
        attentionSoft: '#FAE2CF',
        amberInk: '#794C0B',
        amberCard: '#F8EBD0',
        amberRule: '#B38A42',
        success: '#3E674E',
        danger: '#AF263C',
        onDanger: '#FFFFFF',
        bubbleUser: '#F7E3DB',
        scrollbar: '#CDB0B1',
        scrollbarHover: '#AC8C96',
        termScrollbar: '#68576A',
        shell: '#251D29',
        shellInk: '#EADDE8',
        shellInkStrong: '#FFF3F0',
        shellInkSoft: '#B7A3B6',
        shellDanger: '#F0A3AD',
        shellHairline: '#4B3B4C',
        shellHover: '#382C3A',
        shadowInk: '#372635',
      } },
      dark: { colors: {
        canvas: '#201A22',
        paper: '#2C2430',
        panel: '#3A303E',
        hairline: '#51404F',
        hairlineStrong: '#816477',
        ink: '#F4E9E7',
        inkSoft: '#D8C2CD',
        inkFaint: '#C1A9B8',
        accent: '#F4B29C',
        accentDeep: '#FFCCB6',
        accentSoft: '#49323C',
        accentInk: '#FFCCB6',
        onAccent: '#351D22',
        sectionInk: '#D8C2CD',
        selected: '#443440',
        selectedInk: '#F3BED0',
        attention: '#F5C27F',
        attentionSoft: '#493824',
        amberInk: '#EDCE8E',
        amberCard: '#413821',
        amberRule: '#A48C50',
        success: '#AFD4B0',
        danger: '#F8ABB8',
        onDanger: '#381A29',
        bubbleUser: '#41323D',
        scrollbar: '#705768',
        scrollbarHover: '#9C7F90',
        termScrollbar: '#705B71',
        shell: '#17131D',
        shellInk: '#E5D6E3',
        shellInkStrong: '#F9EDF1',
        shellInkSoft: '#BAA3BC',
        shellDanger: '#F8ABB8',
        shellHairline: '#46384D',
        shellHover: '#302638',
        shadowInk: '#000000',
      } },
    },
  },
  {
    kind: 'kiki-skin', version: 1, id: 'iris',
    name: '鸢尾 Iris × 星幕 Starveil',
    description: 'Violet-white paper and iris ink; indigo-violet layers and silver-lilac controls at night.',
    variants: {
      light: { colors: {
        canvas: '#E7E3F2',
        paper: '#F6F3FC',
        panel: '#FCFAFF',
        hairline: '#D5CEE5',
        hairlineStrong: '#A99BBF',
        ink: '#302B48',
        inkSoft: '#514964',
        inkFaint: '#615775',
        accent: '#6542A5',
        accentDeep: '#4D2F86',
        accentSoft: '#EAE1F7',
        accentInk: '#53318B',
        onAccent: '#FFFFFF',
        sectionInk: '#514964',
        selected: '#E7DEF4',
        selectedInk: '#593793',
        attention: '#98491B',
        attentionSoft: '#F7E5D5',
        amberInk: '#78500B',
        amberCard: '#F7ECCF',
        amberRule: '#AE8E45',
        success: '#306448',
        danger: '#B1294E',
        onDanger: '#FFFFFF',
        bubbleUser: '#ECE6F6',
        scrollbar: '#BEB1D5',
        scrollbarHover: '#9985BA',
        termScrollbar: '#595179',
        shell: '#211D34',
        shellInk: '#DED9F0',
        shellInkStrong: '#F5F0FF',
        shellInkSoft: '#AAA0C5',
        shellDanger: '#F0A5BF',
        shellHairline: '#413857',
        shellHover: '#312A49',
        shadowInk: '#29203F',
      } },
      dark: { colors: {
        canvas: '#171626',
        paper: '#232137',
        panel: '#312F4A',
        hairline: '#44405F',
        hairlineStrong: '#71668F',
        ink: '#EEECFA',
        inkSoft: '#CAC3E2',
        inkFaint: '#ADA4C7',
        accent: '#C5ADF6',
        accentDeep: '#DECCFF',
        accentSoft: '#3D305B',
        accentInk: '#DECCFF',
        onAccent: '#27183F',
        sectionInk: '#CAC3E2',
        selected: '#35304F',
        selectedInk: '#D4C6F7',
        attention: '#F1BE86',
        attentionSoft: '#413226',
        amberInk: '#E8CC87',
        amberCard: '#3C3422',
        amberRule: '#9E884C',
        success: '#A5D6BA',
        danger: '#F3A6C2',
        onDanger: '#34182A',
        bubbleUser: '#36304D',
        scrollbar: '#63577E',
        scrollbarHover: '#9180B2',
        termScrollbar: '#615577',
        shell: '#100F1B',
        shellInk: '#D8D1EF',
        shellInkStrong: '#F3EFFF',
        shellInkSoft: '#ABA0C9',
        shellDanger: '#F3A6C2',
        shellHairline: '#39304E',
        shellHover: '#272238',
        shadowInk: '#000000',
      } },
    },
  },
  {
    kind: 'kiki-skin', version: 1, id: 'contrast',
    name: '高对比 High contrast × 高对比·黑曜 Obsidian',
    description: 'White paper, black text and visible borders; layered charcoal, ice-cyan focus and near-white controls at night.',
    variants: {
      light: { colors: {
        canvas: '#E7E9EC',
        paper: '#FFFFFF',
        panel: '#FFFFFF',
        hairline: '#6E7781',
        hairlineStrong: '#20252C',
        ink: '#0E1116',
        inkSoft: '#20252C',
        inkFaint: '#353B44',
        accent: '#0349B4',
        accentDeep: '#023787',
        accentSoft: '#DBE7FB',
        accentInk: '#023B95',
        onAccent: '#FFFFFF',
        sectionInk: '#0E1116',
        selected: '#DBE7FB',
        selectedInk: '#023B95',
        attention: '#A2280A',
        attentionSoft: '#FDE3D9',
        amberInk: '#6B3D00',
        amberCard: '#FDF0CF',
        amberRule: '#8A5A00',
        success: '#055D20',
        danger: '#A0111F',
        onDanger: '#FFFFFF',
        bubbleUser: '#F3F3F3',
        scrollbar: '#C9CBCE',
        scrollbarHover: '#B3B5B9',
        termScrollbar: '#4D4F53',
        shell: '#0E1116',
        shellInk: '#D4D4D5',
        shellInkStrong: '#F1F1F1',
        shellInkSoft: '#939698',
        shellDanger: '#F0A39C',
        shellHairline: '#303237',
        shellHover: '#212429',
        shadowInk: '#0A0C0F',
      }, fonts: { display: FONT_DISPLAY_NEUTRAL, sans: FONT_SANS_NEUTRAL }, shape: { radius: 8 } },
      dark: { colors: {
        canvas: '#101214',
        paper: '#1C2024',
        panel: '#2A3036',
        hairline: '#8A949E',
        hairlineStrong: '#C5CDD5',
        ink: '#F7F9FB',
        inkSoft: '#E1E6EB',
        inkFaint: '#C2CBD3',
        accent: '#E7EDF4',
        accentDeep: '#FFFFFF',
        accentSoft: '#303840',
        accentInk: '#F4F7FA',
        onAccent: '#11171C',
        sectionInk: '#F7F9FB',
        selected: '#303840',
        selectedInk: '#8DE3F0',
        attention: '#FFD080',
        attentionSoft: '#30343A',
        amberInk: '#F5D58C',
        amberCard: '#30343A',
        amberRule: '#BAA276',
        success: '#A4E0B2',
        danger: '#FFADB8',
        onDanger: '#241318',
        bubbleUser: '#30363C',
        scrollbar: '#8A949E',
        scrollbarHover: '#C5CDD5',
        termScrollbar: '#89939D',
        shell: '#0C0F12',
        shellInk: '#E1E6EB',
        shellInkStrong: '#F7F9FB',
        shellInkSoft: '#BBC6D0',
        shellDanger: '#FFADB8',
        shellHairline: '#89939D',
        shellHover: '#22282E',
        shadowInk: '#000000',
      }, fonts: { display: FONT_DISPLAY_NEUTRAL, sans: FONT_SANS_NEUTRAL }, shape: { radius: 8 } },
    },
  },
];

export function findBuiltinSkin(id: string): SkinFile | undefined {
  return BUILTIN_SKINS.find((skin) => skin.id === id);
}

export const BUILTIN_SKIN_DESCRIPTION_KEYS = {
  paper: 'st.skin.desc.paperPair',
  porcelain: 'st.skin.desc.porcelain',
  celadon: 'st.skin.desc.celadon',
  apricot: 'st.skin.desc.apricot',
  iris: 'st.skin.desc.iris',
  contrast: 'st.skin.desc.contrastPair',
} as const satisfies Readonly<Record<string, I18nKey>>;

export const BUILTIN_SKIN_NAME_KEYS = {
  paper: 'st.skin.name.paper',
  porcelain: 'st.skin.name.porcelain',
  celadon: 'st.skin.name.celadon',
  apricot: 'st.skin.name.apricot',
  iris: 'st.skin.name.iris',
  contrast: 'st.skin.name.contrast',
} as const satisfies Readonly<Record<string, I18nKey>>;

export function builtinSkinDescriptionKey(id: string | undefined): I18nKey | undefined {
  return id !== undefined && Object.hasOwn(BUILTIN_SKIN_DESCRIPTION_KEYS, id)
    ? BUILTIN_SKIN_DESCRIPTION_KEYS[id as keyof typeof BUILTIN_SKIN_DESCRIPTION_KEYS]
    : undefined;
}

export function builtinSkinNameKey(id: string | undefined): I18nKey | undefined {
  return id !== undefined && Object.hasOwn(BUILTIN_SKIN_NAME_KEYS, id)
    ? BUILTIN_SKIN_NAME_KEYS[id as keyof typeof BUILTIN_SKIN_NAME_KEYS]
    : undefined;
}
