import type { AgentExecutorsConfig } from './configSection';

export const BUILTIN_AGENT_EXECUTORS: AgentExecutorsConfig = {
  'grok-acp': {
    label: 'Grok Build',
    protocol: 'acp-v1',
    command: 'grok',
    args: ['--no-auto-update', 'agent', 'stdio'],
    startupTimeoutMs: 70_000,
    shutdownGraceMs: 3_000,
    modelBinding: 'session_config',
    modelConfigCategory: 'model',
    profileDelivery: 'system_prompt_override',
    promptDeliveries: ['replace', 'preamble'],
    defaultProfile: true,
    installHint: 'Install the Grok Build CLI',
    loginCommand: ['grok'],
    diagnostics: [
      { kind: 'env', name: 'XAI_API_KEY', present: 'XAI_API_KEY is present in the host environment.',
        absent: 'Grok reuses the existing CLI login; set XAI_API_KEY only if that is how the vendor CLI is authenticated.' },
      { kind: 'message', severity: 'info', message: 'Spawn order is grok --no-auto-update agent stdio; no auto-approve or bypass flag is used.' },
    ],
    permission: { via: 'argv', flag: '--permission-mode', manual: 'default', auto: 'acceptEdits', yolo: 'bypassPermissions' },
    revision: '2026-08-30.1',
  },
  'codex-app-server': {
    label: 'Codex',
    protocol: 'codex-app-server',
    sources: [
      { id: 'env', kind: 'env', name: 'CODEX_PATH' },
      {
        id: 'desktop',
        kind: 'glob',
        pattern: 'C:/Program Files/WindowsApps/OpenAI.Codex_*/app/resources/codex.exe',
      },
      {
        id: 'vscode-extension',
        kind: 'glob',
        pattern: '~/.vscode/extensions/openai.chatgpt-*/bin/windows-x86_64/codex.exe',
      },
      {
        id: 'cursor-extension',
        kind: 'glob',
        pattern: '~/.cursor/extensions/openai.chatgpt-*/bin/windows-x86_64/codex.exe',
      },
      { id: 'npm-global', kind: 'explicit-path', path: '${APPDATA}/npm/codex.cmd' },
      { id: 'path', kind: 'path-lookup', command: 'codex', requiredBasename: 'codex' },
    ],
    versionProbe: { args: ['--version'] },
    args: [],
    startupTimeoutMs: 150_000,
    shutdownGraceMs: 3_000,
    promptDeliveries: ['append', 'replace', 'preamble'],
    steerDelivery: 'native',
    defaultProfile: true,
    installHint: 'npm i -g @openai/codex@0.158.0',
    loginCommand: ['codex', 'login'],
    auth: { kind: 'codex-account' },
    diagnostics: [
      { kind: 'path', path: '.codex/auth.json', envHome: 'CODEX_HOME',
        present: 'Codex auth state exists at {path}.', absent: 'Codex auth state was not found at {path}; run the vendor login flow first.', absentSeverity: 'warning' },
      { kind: 'message', severity: 'info', message: 'Codex uses app-server --listen stdio:// with on-request approvals and no bypass flag.' },
    ],
    permission: { via: 'turn_param', manual: 'on-request', auto: 'on-request', yolo: 'never' },
    revision: '2026-08-31.1',
  },
  'codex-acp': {
    label: 'Codex ACP',
    protocol: 'acp-v1',
    command: 'codex-acp',
    args: [],
    env: { DISABLE_MCP_CONFIG_FILTERING: 'true' },
    diagnostics: [
      { kind: 'dependency', command: 'codex', args: ['--version'], unavailable: 'Vendor codex CLI is not installed or not executable.', failed: 'codex --version exited with code {code}.' },
      { kind: 'path', path: '.codex/auth.json', envHome: 'CODEX_HOME',
        present: 'Codex auth state exists at {path}.', absent: 'Codex auth state was not found at {path}; run the vendor login flow first.', absentSeverity: 'warning' },
      { kind: 'message', severity: 'info', message: 'DISABLE_MCP_CONFIG_FILTERING=true will be injected into codex-acp.' },
    ],
    startupTimeoutMs: 150_000,
    shutdownGraceMs: 3_000,
    modelBinding: 'session_config',
    modelConfigCategory: 'model',
    revision: '2026-08-31.1',
  },
  'cursor-acp': {
    label: 'Cursor',
    protocol: 'acp-v1',
    sources: [
      { id: 'env', kind: 'env', name: 'CURSOR_AGENT_PATH' },
      { id: 'local-bin', kind: 'explicit-path', path: '~/.local/bin/cursor-agent' },
      {
        id: 'path',
        kind: 'path-lookup',
        command: 'cursor-agent',
        requiredBasename: 'cursor-agent',
      },
      {
        id: 'codeg-managed',
        kind: 'glob',
        pattern: '~/.codeg/**/cursor-agent',
        maxDepth: 8,
      },
    ],
    versionProbe: { args: ['--version'] },
    args: ['acp'],
    shutdownGraceMs: 3_000,
    modelBinding: 'argv',
    modelArgs: ['--model', '{model}'],
    diagnostics: [{ kind: 'message', severity: 'info', message: 'Only cursor-agent is admitted; the unrelated agent shim is never probed.' }],
    revision: '2026-08-31.1',
  },
  'claude-acp': {
    label: 'Claude Code',
    protocol: 'acp-v1',
    command: 'claude-agent-acp',
    args: [],
    shutdownGraceMs: 3_000,
    modelBinding: 'session_config',
    modelConfigCategory: 'model',
    promptDeliveries: ['preamble'],
    defaultProfile: true,
    installHint: 'npm i -g @agentclientprotocol/claude-agent-acp@0.81.2',
    loginCommand: ['claude'],
    auth: { kind: 'command-json', command: 'claude', args: ['auth', 'status', '--json'], loggedInKey: 'loggedIn' },
    diagnostics: [{ kind: 'path', path: '.claude', present: 'Claude login/config directory exists at {path}.',
      absent: 'Claude login/config directory was not found at {path}; run the vendor login flow first.', absentSeverity: 'warning' }],
    permission: { via: 'session_mode', manual: 'default', auto: 'acceptEdits', yolo: 'bypassPermissions' },
    revision: '2026-08-30.1',
  },
  'gemini-acp': {
    label: 'Gemini CLI',
    protocol: 'acp-v1',
    command: 'gemini',
    args: ['--acp'],
    diagnostics: [
      { kind: 'flag', args: ['--help'], stable: '--acp', fallback: '--experimental-acp',
        stableMessage: 'Gemini stable --acp flag is available.',
        fallbackMessage: 'Gemini does not advertise --acp; use --experimental-acp in the trusted descriptor override.',
        missingMessage: 'Gemini help advertises neither --acp nor --experimental-acp.' },
      { kind: 'path', path: '.gemini', present: 'Gemini login/config directory exists at {path}.',
        absent: 'Gemini will reuse its vendor login or API-key environment when present.', absentSeverity: 'info' },
    ],
    shutdownGraceMs: 3_000,
    modelBinding: 'session_config',
    modelConfigCategory: 'model',
    revision: '2026-08-30.1',
  },
  'kimi-acp': {
    label: 'Kimi CLI',
    protocol: 'acp-v1',
    permissionModeMapping: {
      configId: 'mode',
      manual: 'default',
      auto: 'auto',
      yolo: 'yolo',
    },
    command: 'kimi',
    args: ['acp'],
    diagnostics: [{ kind: 'version', min: '0.37.0',
      warning: 'Kimi Code 0.37+ has a reported ACP MCP-injection regression; verify startup before relying on this harness.',
      normal: 'Kimi reuses the existing Kimi Code login and configuration.' }],
    shutdownGraceMs: 3_000,
    modelBinding: 'session_config',
    modelConfigCategory: 'model',
    revision: '2026-08-30.1',
  },
  'opencode-acp': {
    label: 'OpenCode',
    protocol: 'acp-v1',
    command: 'opencode',
    args: ['acp'],
    diagnostics: [{ kind: 'message', severity: 'info', message: 'OpenCode uses the existing vendor login and configuration.' }],
    shutdownGraceMs: 3_000,
    modelBinding: 'session_config',
    modelConfigCategory: 'model',
    revision: '2026-08-30.1',
  },
};
