import type { AgentExecutorsConfig } from './configSection';

export const BUILTIN_AGENT_EXECUTORS: AgentExecutorsConfig = {
  'grok-acp': {
    protocol: 'acp-v1',
    command: 'grok',
    args: ['--no-auto-update', 'agent', 'stdio'],
    startupTimeoutMs: 70_000,
    shutdownGraceMs: 3_000,
    modelBinding: 'session_config',
    modelConfigCategory: 'model',
    profileDelivery: 'system_prompt_override',
    revision: '2026-08-30.1',
  },
  'codex-app-server': {
    protocol: 'codex-app-server',
    sources: [
      { id: 'env', kind: 'env', name: 'CODEX_PATH' },
      {
        id: 'desktop',
        kind: 'glob',
        pattern: 'C:/Program Files/WindowsApps/OpenAI.Codex_*/app/resources/codex.exe',
      },
      {
        id: 'vscode-extension',
        kind: 'glob',
        pattern: '~/.vscode/extensions/openai.chatgpt-*/bin/windows-x86_64/codex.exe',
      },
      {
        id: 'cursor-extension',
        kind: 'glob',
        pattern: '~/.cursor/extensions/openai.chatgpt-*/bin/windows-x86_64/codex.exe',
      },
      { id: 'npm-global', kind: 'explicit-path', path: '${APPDATA}/npm/codex.cmd' },
      { id: 'path', kind: 'path-lookup', command: 'codex', requiredBasename: 'codex' },
    ],
    versionProbe: { args: ['--version'] },
    args: [],
    startupTimeoutMs: 150_000,
    shutdownGraceMs: 3_000,
    revision: '2026-08-31.1',
  },
  'codex-acp': {
    protocol: 'acp-v1',
    command: 'codex-acp',
    args: [],
    env: { DISABLE_MCP_CONFIG_FILTERING: 'true' },
    startupTimeoutMs: 150_000,
    shutdownGraceMs: 3_000,
    modelBinding: 'session_config',
    modelConfigCategory: 'model',
    revision: '2026-08-31.1',
  },
  'cursor-acp': {
    protocol: 'acp-v1',
    sources: [
      { id: 'env', kind: 'env', name: 'CURSOR_AGENT_PATH' },
      { id: 'local-bin', kind: 'explicit-path', path: '~/.local/bin/cursor-agent' },
      {
        id: 'path',
        kind: 'path-lookup',
        command: 'cursor-agent',
        requiredBasename: 'cursor-agent',
      },
      {
        id: 'codeg-managed',
        kind: 'glob',
        pattern: '~/.codeg/**/cursor-agent',
        maxDepth: 8,
      },
    ],
    versionProbe: { args: ['--version'] },
    args: ['acp'],
    shutdownGraceMs: 3_000,
    modelBinding: 'argv',
    modelArgs: ['--model', '{model}'],
    revision: '2026-08-31.1',
  },
  'claude-acp': {
    protocol: 'acp-v1',
    command: 'claude-agent-acp',
    args: [],
    shutdownGraceMs: 3_000,
    modelBinding: 'session_config',
    modelConfigCategory: 'model',
    revision: '2026-08-30.1',
  },
  'gemini-acp': {
    protocol: 'acp-v1',
    command: 'gemini',
    args: ['--acp'],
    shutdownGraceMs: 3_000,
    modelBinding: 'session_config',
    modelConfigCategory: 'model',
    revision: '2026-08-30.1',
  },
  'kimi-acp': {
    protocol: 'acp-v1',
    permissionModeMapping: {
      configId: 'mode',
      manual: 'default',
      auto: 'auto',
      yolo: 'yolo',
    },
    command: 'kimi',
    args: ['acp'],
    shutdownGraceMs: 3_000,
    modelBinding: 'session_config',
    modelConfigCategory: 'model',
    revision: '2026-08-30.1',
  },
  'opencode-acp': {
    protocol: 'acp-v1',
    command: 'opencode',
    args: ['acp'],
    shutdownGraceMs: 3_000,
    modelBinding: 'session_config',
    modelConfigCategory: 'model',
    revision: '2026-08-30.1',
  },
};
