import type { AgentExecutorsConfig } from './configSection';

export const BUILTIN_AGENT_EXECUTORS: AgentExecutorsConfig = {
  'grok-acp': {
    protocol: 'acp-v1',
    command: 'grok',
    args: ['--no-auto-update', 'agent', 'stdio'],
    startupTimeoutMs: 70_000,
    shutdownGraceMs: 3_000,
    modelBinding: 'session_config',
    modelConfigCategory: 'model',
    revision: '2026-08-30.1',
  },
  'codex-acp': {
    protocol: 'acp-v1',
    command: 'codex-acp',
    args: [],
    env: { DISABLE_MCP_CONFIG_FILTERING: 'true' },
    startupTimeoutMs: 150_000,
    shutdownGraceMs: 3_000,
    modelBinding: 'session_config',
    modelConfigCategory: 'model',
    revision: '2026-08-30.1',
  },
  'cursor-acp': {
    protocol: 'acp-v1',
    command: 'cursor-agent',
    args: ['acp'],
    shutdownGraceMs: 3_000,
    modelBinding: 'argv',
    modelArgs: ['--model', '{model}'],
    revision: '2026-08-30.1',
  },
  'claude-acp': {
    protocol: 'acp-v1',
    command: 'claude-agent-acp',
    args: [],
    shutdownGraceMs: 3_000,
    modelBinding: 'session_config',
    modelConfigCategory: 'model',
    revision: '2026-08-30.1',
  },
  'gemini-acp': {
    protocol: 'acp-v1',
    command: 'gemini',
    args: ['--acp'],
    shutdownGraceMs: 3_000,
    modelBinding: 'session_config',
    modelConfigCategory: 'model',
    revision: '2026-08-30.1',
  },
  'kimi-acp': {
    protocol: 'acp-v1',
    command: 'kimi',
    args: ['acp'],
    shutdownGraceMs: 3_000,
    modelBinding: 'session_config',
    modelConfigCategory: 'model',
    revision: '2026-08-30.1',
  },
  'opencode-acp': {
    protocol: 'acp-v1',
    command: 'opencode',
    args: ['acp'],
    shutdownGraceMs: 3_000,
    modelBinding: 'session_config',
    modelConfigCategory: 'model',
    revision: '2026-08-30.1',
  },
};
