import type { AgentExecutorsConfig } from './configSection';

export const BUILTIN_AGENT_EXECUTORS: AgentExecutorsConfig = {
  'grok-acp': {
    label: 'Grok Build',
    protocol: 'acp-v1',
    command: 'grok',
    homeEnv: 'GROK_HOME',
    args: ['--no-auto-update', 'agent', 'stdio'],
    startupTimeoutMs: 70_000,
    shutdownGraceMs: 3_000,
    modelBinding: 'session_config',
    modelConfigCategory: 'model',
    profileDelivery: 'system_prompt_override',
    promptDeliveries: ['replace', 'preamble'],
    defaultProfile: true,
    installHint: 'Install the Grok Build CLI',
    loginCommand: ['grok'],
    diagnostics: [
      { kind: 'env', name: 'XAI_API_KEY', present: 'XAI_API_KEY is present in the host environment.',
        absent: 'Grok reuses the existing CLI login; set XAI_API_KEY only if that is how the vendor CLI is authenticated.' },
      { kind: 'message', severity: 'info', message: 'Grok runs with --permission-mode default in manual/review, acceptEdits in auto, and bypassPermissions in yolo.' },
    ],
    permission: { via: 'argv', flag: '--permission-mode', manual: 'default', auto: 'acceptEdits', yolo: 'bypassPermissions' },
    revision: '2026-08-30.1',
  },
  'codex-app-server': {
    homeEnv: 'CODEX_HOME',
    label: 'Codex',
    protocol: 'codex-app-server',
    sources: [
      { id: 'env', kind: 'env', name: 'CODEX_PATH' },
      {
        id: 'desktop',
        kind: 'glob',
        pattern: 'C:/Program Files/WindowsApps/OpenAI.Codex_*/app/resources/codex.exe',
      },
      {
        id: 'vscode-extension',
        kind: 'glob',
        pattern: '~/.vscode/extensions/openai.chatgpt-*/bin/windows-x86_64/codex.exe',
      },
      {
        id: 'cursor-extension',
        kind: 'glob',
        pattern: '~/.cursor/extensions/openai.chatgpt-*/bin/windows-x86_64/codex.exe',
      },
      { id: 'npm-global', kind: 'explicit-path', path: '${APPDATA}/npm/codex.cmd' },
      { id: 'path', kind: 'path-lookup', command: 'codex', requiredBasename: 'codex' },
    ],
    versionProbe: { args: ['--version'] },
    args: [],
    startupTimeoutMs: 150_000,
    shutdownGraceMs: 3_000,
    promptDeliveries: ['append', 'replace', 'preamble'],
    steerDelivery: 'native',
    defaultProfile: true,
    installHint: 'npm i -g @openai/codex@0.158.0',
    loginCommand: ['codex', 'login'],
    auth: { kind: 'codex-account' },
    diagnostics: [
      { kind: 'path', path: '.codex/auth.json', envHome: 'CODEX_HOME',
        present: 'Codex auth state exists at {path}.', absent: 'Codex auth state was not found at {path}; run the vendor login flow first.', absentSeverity: 'warning' },
      { kind: 'message', severity: 'info', message: 'Codex uses app-server --listen stdio:// with on-request approvals and no bypass flag.' },
    ],
    permission: { via: 'turn_param', manual: 'on-request', auto: 'on-request', yolo: 'never' },
    revision: '2026-08-31.1',
  },
  'codex-acp': {
    homeEnv: 'CODEX_HOME',
    label: 'Codex ACP',
    protocol: 'acp-v1',
    command: 'codex-acp',
    args: [],
    env: { DISABLE_MCP_CONFIG_FILTERING: 'true' },
    diagnostics: [
      { kind: 'dependency', command: 'codex', args: ['--version'], unavailable: 'Vendor codex CLI is not installed or not executable.', failed: 'codex --version exited with code {code}.' },
      { kind: 'path', path: '.codex/auth.json', envHome: 'CODEX_HOME',
        present: 'Codex auth state exists at {path}.', absent: 'Codex auth state was not found at {path}; run the vendor login flow first.', absentSeverity: 'warning' },
      { kind: 'message', severity: 'info', message: 'DISABLE_MCP_CONFIG_FILTERING=true will be injected into codex-acp.' },
    ],
    startupTimeoutMs: 150_000,
    shutdownGraceMs: 3_000,
    modelBinding: 'session_config',
    modelConfigCategory: 'model',
    revision: '2026-08-31.1',
  },
  'cursor-acp': {
    homeEnv: 'CURSOR_CONFIG_DIR',
    label: 'Cursor',
    protocol: 'acp-v1',
    sources: [
      { id: 'env', kind: 'env', name: 'CURSOR_AGENT_PATH' },
      { id: 'local-bin', kind: 'explicit-path', path: '~/.local/bin/cursor-agent' },
      {
        id: 'path',
        kind: 'path-lookup',
        command: 'cursor-agent',
        requiredBasename: 'cursor-agent',
      },
      {
        id: 'codeg-managed',
        kind: 'glob',
        pattern: '~/.codeg/**/cursor-agent',
        maxDepth: 8,
      },
    ],
    versionProbe: { args: ['--version'] },
    args: ['acp'],
    shutdownGraceMs: 3_000,
    modelBinding: 'argv',
    modelArgs: ['--model', '{model}'],
    diagnostics: [{ kind: 'message', severity: 'info', message: 'Only cursor-agent is admitted; the unrelated agent shim is never probed.' }],
    revision: '2026-08-31.1',
  },
  'claude-acp': {
    homeEnv: 'CLAUDE_CONFIG_DIR',
    label: 'Claude Code',
    protocol: 'acp-v1',
    programLabel: 'claude-agent-acp',
    sources: [
      { id: 'env', kind: 'env', name: 'CLAUDE_AGENT_ACP_PATH' },
      { id: 'kiki-managed', kind: 'node-script',
        path: '${KIKI_HOME}/tools/claude-agent-acp/node_modules/@agentclientprotocol/claude-agent-acp/dist/index.js' },
      { id: 'npm-global', kind: 'node-script',
        path: '${APPDATA}/npm/node_modules/@agentclientprotocol/claude-agent-acp/dist/index.js' },
      { id: 'path', kind: 'path-lookup', command: 'claude-agent-acp', requiredBasename: 'claude-agent-acp' },
    ],
    versionProbe: { args: ['--version'] },
    args: [],
    shutdownGraceMs: 3_000,
    modelBinding: 'session_config',
    modelConfigCategory: 'model',
    promptDeliveries: ['preamble'],
    defaultProfile: true,
    installHint: 'npm install --prefix "${KIKI_HOME}/tools/claude-agent-acp" --save-exact @agentclientprotocol/claude-agent-acp@0.84.0',
    loginCommand: ['claude', 'auth', 'login'],
    apiKeyEnv: 'ANTHROPIC_API_KEY',
    auth: { kind: 'claude-credentials', command: 'claude', args: ['auth', 'status', '--json'] },
    diagnostics: [
      { kind: 'dependency', command: 'claude', args: ['--version'], label: 'Claude Code CLI',
        installHint: 'npm install -g @anthropic-ai/claude-code',
        unavailable: 'Claude Code CLI is not installed; Kiki can still run this engine from an API key, but cannot sign in to a subscription or read the sign-in status.',
        failed: 'claude --version exited with code {code}.' },
    ],
    permission: { via: 'session_mode', manual: 'default', auto: 'acceptEdits', yolo: 'bypassPermissions' },
    revision: '2026-09-30.1',
  },
  'gemini-acp': {
    label: 'Gemini CLI',
    protocol: 'acp-v1',
    command: 'gemini',
    homeEnv: 'GEMINI_CLI_HOME',
    args: ['--acp'],
    diagnostics: [
      { kind: 'flag', args: ['--help'], stable: '--acp', fallback: '--experimental-acp',
        stableMessage: 'Gemini stable --acp flag is available.',
        fallbackMessage: 'Gemini does not advertise --acp; use --experimental-acp in the trusted descriptor override.',
        missingMessage: 'Gemini help advertises neither --acp nor --experimental-acp.' },
      { kind: 'path', path: '.gemini', present: 'Gemini login/config directory exists at {path}.',
        absent: 'Gemini will reuse its vendor login or API-key environment when present.', absentSeverity: 'info' },
    ],
    shutdownGraceMs: 3_000,
    modelBinding: 'session_config',
    modelConfigCategory: 'model',
    revision: '2026-08-30.1',
  },
  'kimi-acp': {
    label: 'Kimi CLI',
    protocol: 'acp-v1',
    permissionModeMapping: {
      configId: 'mode',
      manual: 'default',
      auto: 'auto',
      yolo: 'yolo',
    },
    command: 'kimi',
    homeEnv: 'KIMI_CODE_HOME',
    args: ['acp'],
    diagnostics: [{ kind: 'version', min: '0.37.0', maxExclusive: '0.39.0',
      warning: 'This version of Kimi CLI does not accept ACP stdio MCP servers; MCP tools will fail. Upgrade to 0.39.0 or newer.',
      normal: 'Kimi reuses the existing Kimi Code login and configuration.' }],
    supportsMcp: true,
    shutdownGraceMs: 3_000,
    modelBinding: 'session_config',
    modelConfigCategory: 'model',
    revision: '2026-08-30.1',
  },
  'opencode-acp': {
    label: 'OpenCode',
    protocol: 'acp-v1',
    command: 'opencode',
    homeEnv: 'XDG_DATA_HOME',
    args: ['acp'],
    diagnostics: [{ kind: 'message', severity: 'info', message: 'OpenCode uses the existing vendor login and configuration.' }],
    shutdownGraceMs: 3_000,
    modelBinding: 'session_config',
    modelConfigCategory: 'model',
    revision: '2026-08-30.1',
  },
  'openclaw-acp': {
    label: 'OpenClaw', protocol: 'acp-v1', command: 'openclaw', args: ['acp'],
    supportsMcp: false, shutdownGraceMs: 3_000,
    installHint: 'Install OpenClaw with a supported Node.js 22+ runtime',
    diagnostics: [{ kind: 'dependency', command: 'node', args: ['--version'],
      unavailable: 'OpenClaw requires Node.js 22 or newer.', failed: 'Node.js version probe exited with code {code}.' },
    { kind: 'message', severity: 'info', message: 'OpenClaw rejects non-empty ACP mcpServers; configure its own tools in OpenClaw.' }],
    revision: '2026-09-30.1',
  },
  'cline-acp': {
    label: 'Cline', protocol: 'acp-v1', command: 'cline', args: ['--acp'],
    shutdownGraceMs: 3_000,
    installHint: 'npm install -g cline',
    revision: '2026-09-30.1',
  },
  'codebuddy-acp': {
    label: 'CodeBuddy', protocol: 'acp-v1', command: 'codebuddy', args: ['--acp'],
    shutdownGraceMs: 3_000,
    installHint: 'npm install -g @tencent-ai/codebuddy-code',
    revision: '2026-09-30.1',
  },
  'pi-acp': {
    label: 'Pi', protocol: 'acp-v1', command: 'pi-acp', args: [],
    homeEnv: 'PI_CODING_AGENT_DIR', supportsMcp: false, shutdownGraceMs: 3_000,
    installHint: 'Install pi-acp and Pi coding agent separately',
    diagnostics: [{ kind: 'dependency', command: 'pi', args: ['--version'],
      unavailable: 'Pi coding agent is required by pi-acp.', failed: 'Pi version probe exited with code {code}.' },
    { kind: 'message', severity: 'info', message: 'pi-acp launches Pi RPC and does not forward Kiki MCP servers.' }],
    revision: '2026-09-30.1',
  },
  'deepseek-acp': {
    label: 'DeepSeek Harness', protocol: 'acp-v1', command: 'deepseek-acp', args: [],
    homeEnv: 'DSH_HOME', shutdownGraceMs: 3_000, mcpTransports: ['stdio', 'http'],
    installHint: 'Install a compatible deepseek-acp adapter and configure DeepSeek authentication',
    diagnostics: [{ kind: 'message', severity: 'warning',
      message: 'The community deepseek-acp bridge and the vendor dsh-acp have different streaming and MCP support; verify the installed adapter before use.' }],
    revision: '2026-09-30.1',
  },
  'qoder-acp': {
    label: 'Qoder', protocol: 'acp-v1', command: 'qodercli', args: ['--acp'],
    homeEnv: 'QODER_CONFIG_DIR', shutdownGraceMs: 3_000,
    installHint: 'Install Qoder CLI and complete its vendor sign-in flow',
    revision: '2026-09-30.1',
  },
};
