export {
  removeSpaceConfigOverrideRequestSchema,
  spaceRecordSchema,
  spacesResponseSchema,
  spacePresetsResponseSchema,
  createSpaceRequestSchema,
  attachSpaceRequestSchema,
  inspectSpacePathResponseSchema,
  spaceIdParamsSchema,
  updateSpaceRequestSchema,
  updateSpaceResponseSchema,
  sshCopyCandidatesResponseSchema,
  deleteSpaceParamsSchema,
  deleteSpaceRequestSchema,
} from '@kiki/protocol';
