export {
  DEFAULT_SHORTCUT_PREFERENCES,
  SHORTCUT_DEFINITIONS,
  SHORTCUT_CATALOG,
  type FixedShortcutDefinition,
  detectShortcutConflicts,
  matchesShortcut,
  resetShortcutPreferences,
  resolveShortcutBindings,
  shortcutModifierLabel,
  shortcutPreferencesSchema,
  type ShortcutAction,
  type ShortcutChord,
  type ShortcutConflict,
  type ShortcutDefinition,
  type ShortcutKeyEvent,
  type ShortcutPlatform,
  type ShortcutPreferences,
} from '@kiki/protocol';
