import { mkdtemp,readFile,writeFile,rm,readdir } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach,beforeEach,describe,it,expect,vi } from 'vitest';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StreamableHTTPClientTransport } from '@modelcontextprotocol/sdk/client/streamableHttp.js';
import { ISessionManager, ISessionMetadata, ISessionInteractionService, IModelCatalogMutationService, IAgentLifecycleService, IAgentProfileService, IAgentLoopService, IAgentContextMemoryService } from '@kiki/agent-core-v2';
import { createServer } from 'node:http';
import { ISessionApprovalService } from '@kiki/agent-core-v2/session/approval/approval';
import { IMemoryStore } from '@kiki/agent-core-v2/app/memory/memoryStore';
import { IAgentToolResultTruncationService } from '@kiki/agent-core-v2/agent/toolResultTruncation/toolResultTruncation';
import { IAgentBlobService } from '@kiki/agent-core-v2/agent/blob/agentBlobService';
import { startServer,type RunningServer } from '../src/start';
import { TEST_HOST_IDENTITY } from './helpers/hostIdentity';
import { authedFetch } from './helpers/auth';
import { ExternalClientAccess } from '../src/externalClients/access';
import { ExternalClientStore } from '../src/externalClients/store';
import { previewExternalClientMaterials } from '../src/externalClients/materials';
import { workspacePersistenceScope, sessionScopeOf, agentScopeOf } from '@kiki/agent-core-v2/workspace/sessionLifecycle/internal/addressing';
let home:string;let workspace:string;let server:RunningServer;const clients:Client[]=[];
beforeEach(async()=>{vi.stubEnv('KIKI_EXPERIMENTAL_EXTERNAL_CLIENTS','true');vi.stubEnv('KIKI_SEARCH_BACKEND','minidb');vi.stubEnv('KIKI_EXPERIMENTAL_SEARCH_WORKER','false');home=await mkdtemp(join(tmpdir(),'kiki-client-home-'));workspace=await mkdtemp(join(tmpdir(),'kiki-client-work-'));
  await writeFile(join(workspace,'source.txt'),'native source');server=await startServer({hostIdentity:TEST_HOST_IDENTITY,host:'127.0.0.1',port:0,homeDir:home,logLevel:'silent'});});
afterEach(async()=>{await Promise.all(clients.splice(0).map(c=>c.close()));await server?.close();vi.unstubAllEnvs();await rm(home,{recursive:true,force:true,maxRetries:5,retryDelay:100});await rm(workspace,{recursive:true,force:true,maxRetries:5,retryDelay:100});});
async function owner(path:string,body?:unknown,method?:string){const response=await authedFetch(server,`http://127.0.0.1:${server.port}`,`/api/external-clients${path}`,
  {method:method??(body===undefined?'GET':'POST'),headers:body===undefined?undefined:{'content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});
  const result=await response.json() as {code:number;data:any;msg:string};expect(result.code,result.msg).toBe(0);return result.data;}
async function connect(id:string){const {token,mcpUrl}=await owner(`/${id}/credential`,{});const client=new Client({name:'fixture',version:'1.0'},{capabilities:{}});
  await client.connect(new StreamableHTTPClientTransport(new URL(mcpUrl),{requestInit:{headers:{authorization:`Bearer ${token}`}}}));clients.push(client);return {client,token,mcpUrl};}
async function call(client:Client,name:string,args:Record<string,unknown>,meta?:Record<string,unknown>){const result=await client.callTool({name,arguments:args,_meta:meta});
  return result.structuredContent??JSON.parse((result.content as {type:string;text:string}[])[0]!.text);}
async function terminal(client:Client,result:any){for(let attempt=0;attempt<100&&['accepted','running','waiting_approval'].includes(result.state);attempt++){
  await new Promise(resolve=>setTimeout(resolve,20));result=await call(client,'kiki_operation',{operation_id:result.operation_id});}return result;}
async function waiting(client:Client,result:any){for(let attempt=0;attempt<100&&['accepted','running'].includes(result.state);attempt++){
  await new Promise(resolve=>setTimeout(resolve,20));result=await call(client,'kiki_operation',{operation_id:result.operation_id});}return result;}
describe('native external clients',()=>{
  it('runs model-free native tools, splits conversations, persists records and retries without duplicate side effects',async()=>{
    const {connection}=await owner('',{name:'Example client',workspace,mode:'yolo'});
    const {client,mcpUrl,token}=await connect(connection.id);
    const invalidOrigin=await authedFetch(server,`http://127.0.0.1:${server.port}`,'/api/external-clients/listener',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({enabled:true,publicUrl:'https://example.test/base'})});
    expect(await invalidOrigin.json()).toMatchObject({code:40001,details:{code:'invalid_public_origin'}});expect((await owner('/listener')).mcpUrl).toBe(mcpUrl);
    const before=(await owner(`/${connection.id}/sessions`)).sessions;expect(before).toEqual([]);
    const listed=await client.listTools();expect(listed.tools.some(t=>t.name==='Read')).toBe(true);expect(listed.tools.some(t=>t.name==='kiki_respond')).toBe(false);
    expect((await owner(`/${connection.id}/sessions`)).sessions).toEqual([]);
    const missing=await client.callTool({name:'Read',arguments:{path:join(workspace,'source.txt')}});expect(missing.isError).toBe(true);
    const first=await terminal(client,await call(client,'Write',{path:join(workspace,'out.txt'),content:'once',_kiki:{idempotency_key:'write-one'}},{'openai/session':'chat-one'}));
    expect(first.state).toBe('completed');expect(first.result.isError).not.toBe(true);expect(await readFile(join(workspace,'out.txt'),'utf8')).toBe('once');
    const retry=await call(client,'Write',{path:join(workspace,'out.txt'),content:'once',_kiki:{idempotency_key:'write-one'}},{'openai/session':'chat-one'});
    expect(retry.operation_id).toBe(first.operation_id);expect(retry.duplicate).toBe(true);
    const conflict=await client.callTool({name:'Write',arguments:{path:join(workspace,'out.txt'),content:'different',_kiki:{idempotency_key:'write-one'}},_meta:{'openai/session':'chat-one'}});expect(conflict.isError).toBe(true);
    const second=await terminal(client,await call(client,'Read',{path:join(workspace,'source.txt')},{'openai/session':'chat-two'}));expect(second.session_ref).not.toBe(first.session_ref);
    const resumed=await terminal(client,await call(client,'Read',{path:join(workspace,'out.txt')},{'openai/session':'chat-one'}));expect(resumed.session_ref).toBe(first.session_ref);
    const text=await terminal(client,await call(client,'kiki_save_text',{text:'Explicit saved material',kind:'handoff',_kiki:{session_ref:first.session_ref,idempotency_key:'save-one'}}));expect(text.state).toBe('completed');
    const records=(await owner(`/${connection.id}/sessions`)).sessions;expect(records).toHaveLength(2);
    const record=records.find((s:any)=>s.sessionRef===first.session_ref);const main=server.core.accessor.get(ISessionManager).get(record.sessionId)!;
    const metadata=await main.accessor.get(ISessionMetadata).read();expect(metadata.custom?.['externalClient']).toMatchObject({driver:'external'});expect(metadata.agents?.['main']?.model).toBeUndefined();
    const agentDir=join(home,agentScopeOf(sessionScopeOf(workspacePersistenceScope('sessions',record.workspaceId),record.sessionId),'main'));
    const files=await readdir(agentDir);const wireName=files.find(name=>name.includes('wire'))!;
    const wire=await readFile(join(agentDir,wireName),'utf8');expect(wire).toContain('tool.call');expect(wire).toContain('tool.result');expect(wire).toContain('external.text');expect(wire).not.toContain('turn.prompt');
    await server.core.accessor.get(ISessionManager).close(record.sessionId);
    expect(server.core.accessor.get(ISessionManager).get(record.sessionId)).toBeUndefined();
    const materials=await owner(`/sessions/${record.sessionId}/materials`);
    expect(materials).toMatchObject({state:'complete',coverage:{complete:true}});
    expect(materials.items).toEqual(expect.arrayContaining([expect.objectContaining({kind:'saved_text',excerpt:'Explicit saved material',source:{connectionId:connection.id,clientName:'Example client',sessionRef:first.session_ref,driver:'external'}}),expect.objectContaining({kind:'tool_record',toolName:'Write'})]));
    expect(server.core.accessor.get(ISessionManager).get(record.sessionId)).toBeUndefined();
    const lookup=new ExternalClientStore(server.core);
    const bounded=vi.fn(async()=>({snapshot:{items:[],tasks:[],interactions:[],attachments:[],todos:[],prompts:[],meta:{}},bytesRead:2<<20,recordsRead:1,complete:false,incompleteReason:'byte_budget' as const}));
    const partial=await previewExternalClientMaterials(lookup,{readColdSnapshotBounded:bounded},record.sessionId);
    expect(partial).toMatchObject({state:'partial',items:[],coverage:{complete:false,reason:'byte_budget'}});
    expect(bounded).toHaveBeenCalledOnce();expect(bounded).toHaveBeenCalledWith(record.sessionId,'main',expect.objectContaining({maxBytes:2<<20,maxRecords:10_000}));
    expect(await previewExternalClientMaterials(lookup,{readColdSnapshotBounded:async()=>({snapshot:undefined,bytesRead:0,recordsRead:0,complete:false})},record.sessionId)).toMatchObject({state:'unloaded',items:[],coverage:{complete:false}});
    const readBack=await terminal(client,await call(client,'HistoryList',{_kiki:{session_ref:first.session_ref}}));expect(readBack.state).toBe('completed');expect(readBack.result.isError).not.toBe(true);
    let search=await terminal(client,await call(client,'HistorySearch',{query:'Explicit saved material',role:'record',_kiki:{session_ref:first.session_ref}}));
    let page=JSON.parse(search.result.output);for(let i=0;i<5&&page.hits?.length===0&&page.next_cursor;i++) {
      search=await terminal(client,await call(client,'HistorySearch',{cursor:page.next_cursor,_kiki:{session_ref:first.session_ref}}));page=JSON.parse(search.result.output);
    }
    expect(search.result.isError,JSON.stringify(page)).not.toBe(true);expect(JSON.stringify(page)).toContain('Explicit saved material');
    const fork=await owner(`/sessions/${record.sessionId}/continue`,{});expect(fork.sessionId).not.toBe(record.sessionId);
    const forkMeta=await server.core.accessor.get(ISessionManager).get(fork.sessionId)!.accessor.get(ISessionMetadata).read();expect(forkMeta.custom?.['externalClient']).toBeUndefined();
    await owner(`/${connection.id}`,undefined,'DELETE');
    const denied=await fetch(mcpUrl,{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json',accept:'application/json, text/event-stream'},body:JSON.stringify({jsonrpc:'2.0',id:3,method:'tools/list'})});expect(denied.status).toBe(401);
    expect((await fetch(new URL('/api/debug/channels',mcpUrl))).status).toBe(404);
    expect(await owner('/listener',{enabled:false,publicUrl:'https://example.test/'},'PUT')).toMatchObject({state:'stopped',publicUrl:'https://example.test'});
  },90_000);
  it('uses real native approval admission, keeps admitted work across disconnect, and blocks late approval after revoke',async()=>{
    const {connection}=await owner('',{name:'Approval client',workspace,mode:'manual'});
    const {client}=await connect(connection.id);
    const external=await call(client,'kiki_session',{action:'new',_kiki:{idempotency_key:'new'}});
    const ref=external.session_ref;
    const blocked=await terminal(client,await call(client,'Write',{path:join(workspace,'blocked.txt'),content:'blocked',_kiki:{session_ref:ref,idempotency_key:'blocked'}}));
    expect(blocked.result.isError).toBe(true);await expect(readFile(join(workspace,'blocked.txt'))).rejects.toThrow();
    const session=server.core.accessor.get(ISessionManager).get(external.sessionId)!;
    const interaction=session.accessor.get(ISessionInteractionService);interaction.acquireConsumer('local-fixture');
    const pending=await waiting(client,await call(client,'Write',{path:join(workspace,'approved.txt'),content:'once',_kiki:{session_ref:ref,idempotency_key:'approved'}}));
    expect(pending.state).toBe('waiting_approval');const approval=interaction.listPending('approval')[0]!;expect(approval).toBeDefined();
    interaction.releaseConsumer('local-fixture');expect(interaction.listPending('approval')).toHaveLength(1);
    expect((await call(client,'kiki_operation',{operation_id:pending.operation_id})).state).toBe('waiting_approval');
    await owner(`/${connection.id}`,{name:'Renamed client'},'PATCH');
    expect((await call(client,'kiki_operation',{operation_id:pending.operation_id})).state).toBe('waiting_approval');
    await owner(`/${connection.id}`,{name:'Renamed client',workspace:join(workspace,'.'),mode:connection.mode,tools:connection.tools.toReversed(),allowCommands:connection.allowCommands,memoryScopes:connection.memoryScopes.toReversed(),historyScope:connection.historyScope,enabled:true},'PATCH');
    expect(interaction.listPending('approval')).toHaveLength(1);expect((await call(client,'kiki_operation',{operation_id:pending.operation_id})).state).toBe('waiting_approval');
    session.accessor.get(ISessionApprovalService).decide(approval.id,{decision:'approved'});
    const approved=await terminal(client,await call(client,'kiki_operation',{operation_id:pending.operation_id}));expect(approved.state).toBe('completed');expect(approved.result.isError).not.toBe(true);
    expect(await readFile(join(workspace,'approved.txt'),'utf8')).toBe('once');
    interaction.acquireConsumer('local-fixture');
    const narrowed=await waiting(client,await call(client,'Write',{path:join(workspace,'narrowed.txt'),content:'never',_kiki:{session_ref:ref,idempotency_key:'narrowed'}}));expect(narrowed.state).toBe('waiting_approval');
    const narrowApproval=interaction.listPending('approval')[0]!;
    await owner(`/${connection.id}`,{tools:connection.tools.filter((tool:string)=>tool!=='Write')},'PATCH');
    session.accessor.get(ISessionApprovalService).decide(narrowApproval.id,{decision:'approved'});
    expect((await call(client,'kiki_operation',{operation_id:narrowed.operation_id})).state).not.toBe('completed');
    await expect(readFile(join(workspace,'narrowed.txt'))).rejects.toThrow();expect(await readFile(join(workspace,'approved.txt'),'utf8')).toBe('once');
    await owner(`/${connection.id}`,{tools:connection.tools,mode:'yolo'},'PATCH');
    const upgraded=await terminal(client,await call(client,'Write',{path:join(workspace,'upgraded.txt'),content:'effective mode',_kiki:{session_ref:ref,idempotency_key:'upgraded'}}));expect(upgraded.state).toBe('completed');expect(upgraded.result.isError).not.toBe(true);
    await owner(`/${connection.id}`,{mode:'manual'},'PATCH');
    const late=await waiting(client,await call(client,'Write',{path:join(workspace,'late.txt'),content:'never',_kiki:{session_ref:ref,idempotency_key:'late'}}));expect(late.state).toBe('waiting_approval');
    const lateApproval=interaction.listPending('approval')[0]!;
    await owner(`/${connection.id}`,undefined,'DELETE');session.accessor.get(ISessionApprovalService).decide(lateApproval.id,{decision:'approved'});
    await expect(readFile(join(workspace,'late.txt'))).rejects.toThrow();
  },90_000);
  it('restricts native history refs, memory scope and home files while paging historical media bytes',async()=>{
    const {connection}=await owner('',{name:'Scoped client',workspace,mode:'yolo'});const {client}=await connect(connection.id);
    const external=await call(client,'kiki_session',{action:'new',_kiki:{idempotency_key:'new'}});const ref=external.session_ref;
    const denied=await terminal(client,await call(client,'Read',{path:join(home,'config.toml'),_kiki:{session_ref:ref}}));expect(denied.result.isError).toBe(true);
    const peer=await terminal(client,await call(client,'HistorySearch',{query:'secret',scope:'peer',_kiki:{session_ref:ref}}));expect(peer.result.isError).toBe(true);
    const privateEntry=await server.core.accessor.get(IMemoryStore).put({action:'create',scope:{kind:'global'},type:'feedback',title:'Private host rule',body:'secret material',reason:'Fixture',source:{writer:'user'},basis:{kind:'human',note:'Fixture host guidance',refs:[]}});
    const global=await terminal(client,await call(client,'MemorySearch',{scope:'global',query:'secret',_kiki:{session_ref:ref}}));expect(JSON.stringify(global.result)).not.toContain('secret material');
    const hidden=await terminal(client,await call(client,'MemoryRead',{id:privateEntry.entry.id,_kiki:{session_ref:ref}}));expect(JSON.stringify(hidden.result)).not.toContain('secret material');
    const bytes=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aGN8AAAAASUVORK5CYII=','base64');
    await writeFile(join(workspace,'pixel.png'),bytes);
    const media=await terminal(client,await call(client,'ReadMediaFile',{path:join(workspace,'pixel.png'),_kiki:{session_ref:ref}}));expect(media.result.isError).not.toBe(true);
    await writeFile(join(workspace,'pixel.png'),'changed current host bytes');
    const mediaPart=media.result.output.findIndex((part:any)=>part.type==='image_url');expect(mediaPart).toBeGreaterThanOrEqual(0);
    const original=await client.callTool({name:'kiki_operation',arguments:{operation_id:media.operation_id,action:'read',part:mediaPart,offset:0,limit:256000}});
    const resource=(original.content as any[]).find(part=>part.type==='resource');expect(resource).toBeDefined();expect(Buffer.from(resource.resource.blob,'base64')).toEqual(bytes);
    const {connection:other}=await owner('',{name:'Another client',workspace,mode:'yolo'});const {client:otherClient}=await connect(other.id);
    expect((await otherClient.callTool({name:'kiki_operation',arguments:{operation_id:media.operation_id,action:'read',part:0}})).isError).toBe(true);
    await terminal(client,await call(client,'kiki_save_text',{text:'Private saved material',kind:'note',_kiki:{session_ref:ref,idempotency_key:'note'}}));
    const found=await terminal(client,await call(client,'HistorySearch',{query:'Private saved material',role:'record',_kiki:{session_ref:ref}}));const foundPage=JSON.parse(found.result.output);expect(foundPage.hits[0].ref).toBeDefined();
    const otherSession=await call(otherClient,'kiki_session',{action:'new',_kiki:{idempotency_key:'new'}});
    const crossed=await terminal(otherClient,await call(otherClient,'HistoryRead',{ref:foundPage.hits[0].ref,_kiki:{session_ref:otherSession.session_ref}}));expect(crossed.result.isError).toBe(true);expect(JSON.stringify(crossed.result)).not.toContain('Private saved material');
    const foreignWorkspace=await mkdtemp(join(workspace,'foreign-work-'));
    const {connection:foreign}=await owner('',{name:'Foreign workspace client',workspace:foreignWorkspace,mode:'yolo'});const foreignClient=await connect(foreign.id);
    const foreignSession=await call(foreignClient.client,'kiki_session',{action:'new',_kiki:{idempotency_key:'new'}});
    await owner(`/${connection.id}`,{historyScope:'workspace'},'PATCH');
    const store=new ExternalClientStore(server.core);const record=await store.session(connection.id,ref);
    await expect(new ExternalClientAccess(store,record).history(undefined,foreignSession.sessionId)).rejects.toThrow('outside the shared workspace');
    const nativeMain=server.core.accessor.get(ISessionManager).get(external.sessionId)!.accessor.get(IAgentLifecycleService).get('main')!;
    const blobBytes=Buffer.concat([bytes,Buffer.alloc(4096)]);
    const blobParts=await nativeMain.accessor.get(IAgentBlobService).offloadParts([{type:'image_url',imageUrl:{url:`data:image/png;base64,${blobBytes.toString('base64')}`}}]);
    expect(JSON.stringify(blobParts)).toContain('blobref:image/png;');
    const blobOperation=await store.admit(connection.id,ref,'ReadMediaFile',{path:'saved-native-blob-fixture'},'native-blob-fixture');
    await store.saveOperation({...blobOperation.operation,state:'completed',result:{output:blobParts},updatedAt:Date.now()});
    const blobPage=await client.callTool({name:'kiki_operation',arguments:{operation_id:blobOperation.operation.id,action:'read',part:0,limit:256000}});
    const blobResource=(blobPage.content as any[]).find(part=>part.type==='resource');expect(blobResource.resource.mimeType).toBe('image/png');expect(Buffer.from(blobResource.resource.blob,'base64')).toEqual(blobBytes);
    expect((await otherClient.callTool({name:'kiki_operation',arguments:{operation_id:blobOperation.operation.id,action:'read',part:0}})).isError).toBe(true);
    const large=Array.from({length:50},(_,index)=>`${'x'.repeat(1800)}${index===49?'END_OF_SAVED_ARTIFACT':''}`).join('\n');
    const spilled=await nativeMain.accessor.get(IAgentToolResultTruncationService).truncateForModel({toolName:'fixture',toolCallId:'large-result',result:{output:large}});
    const artifact=/output_path: ([^\n]+)/.exec(spilled.output)?.[1];expect(artifact).toBeDefined();
    const readArtifact=await terminal(client,await call(client,'Read',{path:artifact,n_lines:100,_kiki:{session_ref:ref}}));expect(readArtifact.result.isError).not.toBe(true);expect(readArtifact.result.mcp_truncated).toBe(true);expect(readArtifact.result.output).not.toContain('END_OF_SAVED_ARTIFACT');
    const fullArtifact=await client.callTool({name:'kiki_operation',arguments:{operation_id:readArtifact.operation_id,action:'read',offset:0,limit:256000}});
    expect(JSON.stringify(fullArtifact.content)).toContain('END_OF_SAVED_ARTIFACT');expect(fullArtifact.structuredContent).toMatchObject({complete:true});
    const deniedArtifact=await terminal(otherClient,await call(otherClient,'Read',{path:artifact,_kiki:{session_ref:otherSession.session_ref}}));expect(deniedArtifact.result.isError).toBe(true);
  },90_000);
  it('protects private home nested in a workspace from recursive native searches',async()=>{
    await server.close();await rm(home,{recursive:true,force:true,maxRetries:5,retryDelay:100});
    home=join(workspace,'private-host');server=await startServer({hostIdentity:TEST_HOST_IDENTITY,host:'127.0.0.1',port:0,homeDir:home,logLevel:'silent'});
    await writeFile(join(home,'host-secret.txt'),'NATIVE_PRIVATE_MARKER');
    const {connection}=await owner('',{name:'Nested home client',workspace,mode:'yolo'});const {client}=await connect(connection.id);
    const external=await call(client,'kiki_session',{action:'new',_kiki:{idempotency_key:'new'}});
    const grep=await terminal(client,await call(client,'Grep',{pattern:'NATIVE_PRIVATE_MARKER',path:workspace,_kiki:{session_ref:external.session_ref}}));
    expect(grep.result.isError).toBe(true);expect(grep.result.output).toContain('Narrow the search path');expect(grep.result.output).not.toContain('NATIVE_PRIVATE_MARKER');
    const glob=await terminal(client,await call(client,'Glob',{pattern:'**/*',path:workspace,_kiki:{session_ref:external.session_ref}}));expect(glob.result.isError).toBe(true);
    const read=await terminal(client,await call(client,'Read',{path:join(workspace,'source.txt'),_kiki:{session_ref:external.session_ref}}));expect(read.result.isError).not.toBe(true);expect(read.result.output).toContain('native source');
    await server.core.accessor.get(ISessionManager).close(external.sessionId);
    const agentDir=join(home,agentScopeOf(sessionScopeOf(workspacePersistenceScope('sessions',external.workspaceId),external.sessionId),'main'));
    const wireName=(await readdir(agentDir)).find(name=>name.includes('wire'))!;
    const records=(await readFile(join(agentDir,wireName),'utf8')).split('\n').filter(Boolean).map(line=>JSON.parse(line));
    expect(records.filter(record=>record.type==='external.activity'&&record.phase==='failed')).toHaveLength(2);
  },90_000);
  it('runs a native child with an isolated fake provider and restores an accepted key without rerun after host restart',async()=>{
    const requests:unknown[]=[];
    const provider=createServer((request,response)=>{let body='';request.on('data',chunk=>{body+=String(chunk);});request.on('end',()=>{
      requests.push(JSON.parse(body));response.writeHead(200,{'content-type':'text/event-stream'});
      response.end(`data: ${JSON.stringify({id:'fixture-response',choices:[{index:0,delta:{content:'Child completed.'},finish_reason:'stop'}],usage:{prompt_tokens:1,completion_tokens:1,total_tokens:2}})}\n\ndata: [DONE]\n\n`);
    });});
    await new Promise<void>(resolve=>provider.listen(0,'127.0.0.1',resolve));const address=provider.address();if(address===null||typeof address==='string')throw new Error('Fixture provider failed to bind');
    try {
      const mutations=server.core.accessor.get(IModelCatalogMutationService);
      await mutations.createProvider({id:'fixture',type:'openai',base_url:`http://127.0.0.1:${address.port}/v1`,api_key:'fixture'});
      await mutations.createModel({id:'fixture-model',provider_id:'fixture',remote_id:'fixture-model',max_context_size:100000});
      const {connection}=await owner('',{name:'Child client',workspace,mode:'yolo'});const {client}=await connect(connection.id);
      const external=await call(client,'kiki_session',{action:'new',_kiki:{idempotency_key:'new'}});
      const args={prompt:'Return Child completed.',description:'Complete fixture child',name:'fixture_child',model_alias:'fixture-model',background:true,_kiki:{session_ref:external.session_ref,idempotency_key:'child'}};
      const child=await terminal(client,await call(client,'AgentRun',args));expect(child.state).toBe('completed');expect(child.result.isError,JSON.stringify(child.result)).not.toBe(true);
      const taskId=/task_id: (\S+)/.exec(child.result.output)?.[1];expect(taskId).toBeDefined();
      const session=server.core.accessor.get(ISessionManager).get(external.sessionId)!;const agents=session.accessor.get(IAgentLifecycleService);
      expect(agents.list()).toHaveLength(2);await agents.list().find(agent=>agent.id!=='main')!.accessor.get(IAgentLoopService).settled();
      const output=await terminal(client,await call(client,'TaskOutput',{task_id:taskId,_kiki:{session_ref:external.session_ref}}));expect(output.result.output).toContain('Child completed.');
      expect(agents.get('main')!.accessor.get(IAgentProfileService).data()).toMatchObject({driver:'external',modelAlias:undefined});
      await terminal(client,await call(client,'kiki_save_text',{text:'Saved continuation material',kind:'handoff',_kiki:{session_ref:external.session_ref,idempotency_key:'handoff'}}));
      const fork=await owner(`/sessions/${external.sessionId}/continue`,{});const target=server.core.accessor.get(ISessionManager).get(fork.sessionId)!;
      expect(target.accessor.get(IAgentLifecycleService).list()).toHaveLength(1);expect(agents.list()).toHaveLength(2);
      const targetMain=target.accessor.get(IAgentLifecycleService).get('main')!;
      expect(JSON.stringify(targetMain.accessor.get(IAgentContextMemoryService).get())).toContain('Saved continuation material');
      expect(JSON.stringify(targetMain.accessor.get(IAgentContextMemoryService).get())).toContain('external_record');
      await targetMain.accessor.get(IAgentProfileService).bind({model:'fixture-model'});expect(targetMain.accessor.get(IAgentProfileService).data().driver).toBeUndefined();
      expect(requests.length).toBeGreaterThan(0);const requestCount=requests.length;
      expect((await call(client,'AgentRun',args)).duplicate).toBe(true);expect(agents.list()).toHaveLength(2);expect(requests).toHaveLength(requestCount);
      await Promise.all(clients.splice(0).map(c=>c.close()));await server.close();
      server=await startServer({hostIdentity:TEST_HOST_IDENTITY,host:'127.0.0.1',port:0,homeDir:home,logLevel:'silent'});
      const restored=await connect(connection.id);const replay=await call(restored.client,'AgentRun',args);expect(replay.operation_id).toBe(child.operation_id);expect(replay.duplicate).toBe(true);expect(requests).toHaveLength(requestCount);
      expect((await owner(`/${connection.id}/sessions`)).sessions).toHaveLength(1);
    } finally {await new Promise<void>((resolve,reject)=>provider.close(error=>{if(error)reject(error);else resolve();}));}
  },90_000);
});
