/**
 * Prototype copy (zh). These strings exist only for the variant previews; the
 * chosen direction moves its copy into the session-core i18n dictionaries.
 * Real components reused inside the previews (approval / question cards,
 * context chips) keep their own i18n keys.
 */

export const COPY = {
  sessionTitle: '分页与长会话',
  sessionMeta: 'kiki · main',
  placeholder: '让 kiki 做点什么…',
  placeholderBusy: '继续补充 — 发出后会排在当前工作之后',
  placeholderEphemeral: '临时对话，关闭后不保留记录',
  placeholderOffline: '连接恢复后才能发送，草稿会保留',
  agent: 'Kiki',
  model: 'Kiki Pro',
  effort: '高',
  planChip: '计划',
  perm: { manual: '每步询问', auto: '自动', review: '替我审批', yolo: '完全放行' },
  ephemeralTag: '临时对话',
  replyingTo: (name: string) => `回复 ${name}`,

  working: '正在工作',
  compacting: '正在压缩上下文',
  waitingOnYou: '等你处理',
  lastOutput: (s: number) => (s <= 5 ? '刚刚有输出' : `${s} 秒前有输出`),
  idleWaiting: '空闲 · 排队消息等待条件满足',
  reconnecting: '连接中断，正在重连',
  offline: '已断开连接',
  reconnectNow: '立即重连',
  resyncing: '正在重新同步',
  sendPausedShort: '暂停发送',
  recovered: (n: number) => `${n} 条排队消息随会话恢复`,
  recoveredConfirm: '继续发送',

  queued: '待发送',
  queuedCount: (n: number) => `${n} 条待发送`,
  queueNth: (n: number) => `第 ${n} 条`,
  steering: '插入中',
  steeringHint: '下一步开始前送达',
  sendNow: '立即插入',
  sendNowTitle: '不等这一轮结束，插入到正在进行的工作里',
  edit: '编辑',
  remove: '移除',
  clearAll: '全部清除',
  moreQueued: (n: number) => `还有 ${n} 条`,
  timing: { agent_idle: '空闲后', subagents_done: '子智能体完成后', tasks_done: '任务完成后' },
  attachmentsN: (n: number) => `${n} 个附件`,
  editingHere: '正在输入框中编辑',
  holdNotice: '编辑期间，这条和后面的消息暂停发送',
  editConfirm: '保存修改',
  editCancel: '放弃修改',

  needsYou: '需要你处理',
  needsYouN: (n: number) => `需要你 ${n}`,
  approvalsN: (n: number) => `${n} 项待批准`,
  questionsN: (n: number) => `${n} 个待回答`,
  approveAll: '全部批准',
  fromAgent: (name: string) => `来自 ${name}`,
  later: '稍后',
  draftKept: '草稿已保留',
  backToInput: '回到输入框',
  nOfM: (n: number, m: number) => `${n} / ${m}`,
  approvalRow: (tool: string, action: string) => `${tool} · ${action}`,
  question: '问题',
  approval: '批准',

  notes: '批注',
  notesUnsent: (n: number) => `${n} 条随下条消息发送`,
  notesSent: (n: number) => `${n} 条已在会话中`,

  context: (p: number) => `上下文 ${p}%`,
  contextHigh: '上下文快满了',
  compactNow: '立即压缩',

  shortcutQueue: 'Enter 排队',
  shortcutSteer: '⌘/Ctrl+Enter 立即插入',
  shortcutEdit: '↑ 编辑最后一条',
  footerHint: 'Enter 发送 · Shift+Enter 换行 · / 技能 · @ 文件',

  stop: '停止',
  send: '发送',
  queueSend: '加入待发送',
  jumpToQueue: (n: number) => `${n} 条待发送`,
  stateOf: '状态',
} as const;
